INTERFACE
SUBROUTINE CLOUDSC2 ( &
 & KIDIA , KFDIA , KLON , KTDIA , KLEV , LDRAIN1D, &
 & PTSPHY, &
 & PAPHP1 , PAPP1 ,  PQM1  , PQS  , PTM1 ,  PL ,  PI, &
 & PLUDE  , PLU   , PMFU   , PMFD ,&
 & PTENT  , PGTENT, PTENQ  , PGTENQ, &
 & PTENL  , PGTENL, PTENI  , PGTENI, PSUPSAT, &
 & PCLC   , PFPLSL , PFPLSN, &
 & PFHPSL , PFHPSN, PCOVPTOT, & 
 & YDCST, YDTHF, YHNC, YPHLI, YCLD, YCLDP )  
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMCST   , ONLY : TOMCST
USE YOETHF   , ONLY : TOETHF
USE YOPHNC   , ONLY : TPHNC
USE YOEPHLI  , ONLY : TEPHLI
USE YOECLD   , ONLY : TECLD
USE YOECLDP  , ONLY : TECLDP
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KTDIA 
LOGICAL           ,INTENT(IN)    :: LDRAIN1D 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSPHY 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPHP1(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPP1(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQM1(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQS(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTM1(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PL(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PI(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLUDE(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLU(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMFU(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMFD(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTENT(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTENQ(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTENL(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTENI(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGTENT(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGTENQ(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGTENL(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGTENI(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSUPSAT(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCLC(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFPLSL(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFPLSN(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFHPSL(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFHPSN(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCOVPTOT(KLON,KLEV)
TYPE(TOMCST)      ,INTENT(IN) :: YDCST
TYPE(TOETHF)      ,INTENT(IN) :: YDTHF
TYPE(TPHNC)       ,INTENT(IN) :: YHNC
TYPE(TEPHLI)      ,INTENT(IN) :: YPHLI
TYPE(TECLD)       ,INTENT(IN) :: YCLD
TYPE(TECLDP)      ,INTENT(IN) :: YCLDP
END SUBROUTINE CLOUDSC2
END INTERFACE
