SUBROUTINE CUADJTQSAD &
 &(KIDIA,    KFDIA,    KLON,     KLEV,&
 & KK,&
 & PSP5,     PT5,      PQ5,&
 & PSP,      PT,       PQ,       LDFLAG,   KCALL)  

!**   *CUADJTQSAD* - SIMPLIFIED VERSION OF MOIST ADJUSTMENT
!                    (Adjoint)

!     J.F. MAHFOUF      ECMWF
!      20180303 : Gabor: Just a comment line to force recompilation due to
!                        compiler wrapper optimization exception list change
         

!     PURPOSE.
!     --------
!     TO PRODUCE T,Q AND L VALUES FOR CLOUD ASCENT

!     INTERFACE
!     ---------
!     THIS ROUTINE IS CALLED FROM SUBROUTINES:

!       *CONDAD*     
!       *CUBMADJAD*  
!       *CUBMDAD*    

!     INPUT ARE UNADJUSTED T AND Q VALUES,
!     IT RETURNS ADJUSTED VALUES OF T AND Q

!     PARAMETER     DESCRIPTION                                   UNITS
!     ---------     -----------                                   -----
!     INPUT PARAMETERS (INTEGER):

!    *KIDIA*        START POINT
!    *KFDIA*        END POINT
!    *KLON*         NUMBER OF GRID POINTS PER PACKET
!    *KLEV*         NUMBER OF LEVELS
!    *KK*           LEVEL
!    *KCALL*        DEFINES CALCULATION AS
!                      KCALL=0  ENV. T AND QS IN*CUINI*
!                      KCALL=1  CONDENSATION IN UPDRAFTS  (E.G. CUBASE, CUASC)
!                      KCALL=2  EVAPORATION IN DOWNDRAFTS (E.G. CUDLFS,CUDDRAF)

!     INPUT PARAMETERS (LOGICAL):

!    *LDLAND*       LAND-SEA MASK (.TRUE. FOR LAND POINTS)

!     INPUT PARAMETERS (REAL):

!    *PSP5*         PRESSURE                                    (Trajectory)
!    *PSP*          PRESSURE                                        PA

!     UPDATED PARAMETERS (REAL):

!    *PT5*          TEMPERATURE                                (Trajectory) 
!    *PQ5*          SPECIFIC HUMIDITY                          (Trajectory) 
!    *PT*           TEMPERATURE                                     K
!    *PQ*           SPECIFIC HUMIDITY                             KG/KG

!----------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
!USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK

USE YOMCST   , ONLY : RETV     ,RLVTT    ,RLSTT    ,RTT
USE YOETHF   , ONLY : R2ES     ,R3LES    ,R3IES    ,R4LES    ,&
 & R4IES    ,R5LES    ,R5IES    ,R5ALVCP  ,R5ALSCP  ,&
 & RALVDCP  ,RALSDCP  ,RTWAT    ,RTICE    ,RTICECU  ,&
 & RTWAT_RTICE_R      ,RTWAT_RTICECU_R  

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KK 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSP5(KLON) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PT5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PQ5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSP(KLON) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PT(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PQ(KLON,KLEV) 
LOGICAL           ,INTENT(IN)    :: LDFLAG(KLON) 
INTEGER(KIND=JPIM),INTENT(IN)    :: KCALL 
REAL(KIND=JPRB) ::     ZCOND5(KLON),           ZQP5(KLON)

REAL(KIND=JPRB) ::     ZCOND(KLON),            ZQP(KLON)

REAL(KIND=JPRB) ::     Z3ES(KLON),             Z4ES(KLON),&
 & Z5ALCP(KLON),           ZALDCP(KLON)  

REAL(KIND=JPRB) ::     ZTARG5(KLON),           ZFOEEW5(KLON),&
 & ZQSAT5(KLON),           ZCOR5(KLON),&
 & Z2S5(KLON),             ZCOND15(KLON)  

REAL(KIND=JPRB) ::     ZTARG(KLON),            ZFOEEW(KLON),&
 & ZQSAT(KLON),            ZCOR(KLON),&
 & Z2S(KLON),              ZCOND1(KLON)  

!*        EXTRA LOCAL STORAGE FOR TRAJECTORY ARRAYS

REAL(KIND=JPRB) ::     ZQSAT55C(KLON),         ZCOR55A(KLON),&
 & Z2S55A(KLON),           ZTARG55A(KLON),&
 & ZQSAT55A(KLON),         ZFOEEW55A(KLON),&
 & ZQSAT55D(KLON),         ZCOR55B(KLON),&
 & Z2S55B(KLON),           ZTARG55B(KLON),&
 & ZQSAT55B(KLON),         ZFOEEW55B(KLON),&
 & ZQ55A(KLON),            ZQ55B(KLON)  

LOGICAL ::  LLTEST1(KLON),          LLTEST2(KLON),&
 & LLTEST3(KLON),          LLTEST4(KLON),&
 & LLTEST5      ,          LLTEST6   

INTEGER(KIND=JPIM) :: ISUM, JL

REAL(KIND=JPRB) :: ZQMAX
!REAL(KIND=JPRB) :: ZHOOK_HANDLE

!DIR$ VFUNCTION EXPHF
#include "fcttre.func.h"
!----------------------------------------------------------------------

!     1.           DEFINE CONSTANTS
!                  ----------------

!IF (LHOOK) CALL DR_HOOK('CUADJTQSAD',0,ZHOOK_HANDLE)
ZQMAX=0.5_JPRB

!----------------------------------------------------------------------

!*              ------  TRAJECTORY COMPUTATIONS  ------

!----------------------------------------------------------------------

!     2.           CALCULATE CONDENSATION AND ADJUST T AND Q ACCORDINGLY
!                  -----------------------------------------------------

!*    ICE-WATER THERMODYNAMICAL FUNCTIONS

DO JL=KIDIA,KFDIA
  IF (PT5(JL,KK) > RTT) THEN
    Z3ES(JL)=R3LES
    Z4ES(JL)=R4LES
    Z5ALCP(JL)=R5ALVCP
    ZALDCP(JL)=RALVDCP
  ELSE
    Z3ES(JL)=R3IES
    Z4ES(JL)=R4IES
    Z5ALCP(JL)=R5ALSCP
    ZALDCP(JL)=RALSDCP
  ENDIF
ENDDO

IF (KCALL == 1 ) THEN

  ISUM=0
!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    IF(LDFLAG(JL)) THEN
      ZQP5(JL)=1.0_JPRB/PSP5(JL)
      ZTARG5(JL)=PT5(JL,KK)
      ZFOEEW5(JL)=R2ES*EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/(ZTARG5(JL)-Z4ES(JL)))
      ZFOEEW55B(JL)=ZFOEEW5(JL)
      ZQSAT5(JL)=ZQP5(JL)*ZFOEEW5(JL)
      LLTEST2(JL)=ZQSAT5(JL) > ZQMAX
      IF (ZQSAT5(JL) > ZQMAX) THEN
        ZQSAT5(JL)=ZQMAX
      ENDIF
      ZCOR5(JL)=1.0_JPRB/(1.0_JPRB-RETV*ZQSAT5(JL))
      ZQSAT55D(JL)=ZQSAT5(JL)
      ZQSAT5(JL)=ZQSAT5(JL)*ZCOR5(JL)
      ZTARG55B(JL)=ZTARG5(JL)
      Z2S5(JL)=    Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**2
      ZQSAT55B(JL)=ZQSAT5(JL)
      ZCOR55B(JL)=ZCOR5(JL)
      Z2S55B(JL)=Z2S5(JL)
      ZQ55B(JL)=PQ5(JL,KK)
      ZCOND5(JL)=(PQ5(JL,KK)-ZQSAT5(JL))/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      LLTEST4(JL)=ZCOND5(JL) < 0.0_JPRB
      IF (ZCOND5(JL) < 0.0_JPRB) THEN
        ZCOND5(JL)=0.0_JPRB
      ENDIF
      PT5(JL,KK)=PT5(JL,KK)+ZALDCP(JL)*ZCOND5(JL)
      PQ5(JL,KK)=PQ5(JL,KK)-ZCOND5(JL)
      IF(ZCOND5(JL) /= 0.0_JPRB) ISUM=ISUM+1
    ELSE
      ZCOND5(JL)=0.0_JPRB
    ENDIF
  ENDDO

  LLTEST6=ISUM == 0
  IF(ISUM == 0) GO TO 2315

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    LLTEST3(JL)=LDFLAG(JL).AND.ZCOND5(JL) /= 0.0_JPRB
    IF(LDFLAG(JL).AND.ZCOND5(JL) /= 0.0_JPRB) THEN
      ZTARG5(JL)=PT5(JL,KK)
      ZFOEEW5(JL)=R2ES*EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/(ZTARG5(JL)-Z4ES(JL)))
      ZFOEEW55A(JL)=ZFOEEW5(JL)
      ZQSAT5(JL)=ZQP5(JL)*ZFOEEW5(JL)
      LLTEST1(JL)=ZQSAT5(JL) > ZQMAX
      IF (ZQSAT5(JL) > ZQMAX) THEN
        ZQSAT5(JL)=ZQMAX
      ENDIF
      ZCOR5(JL)=1.0_JPRB/(1.0_JPRB-RETV*ZQSAT5(JL))
      ZQSAT55C(JL)=ZQSAT5(JL)
      ZQSAT5(JL)=ZQSAT5(JL)*ZCOR5(JL)
      ZTARG55A(JL)=ZTARG5(JL)
      Z2S5(JL)=Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**2
      ZQSAT55A(JL)=ZQSAT5(JL)
      ZCOR55A(JL)=ZCOR5(JL)
      Z2S55A(JL)=Z2S5(JL)
      ZQ55A(JL)=PQ5(JL,KK)
      ZCOND15(JL)=(PQ5(JL,KK)-ZQSAT5(JL))/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      PT5(JL,KK)=PT5(JL,KK)+ZALDCP(JL)*ZCOND15(JL)
      PQ5(JL,KK)=PQ5(JL,KK)-ZCOND15(JL)
    ENDIF
  ENDDO

  2315 CONTINUE

ENDIF

IF(KCALL == 2) THEN

  ISUM=0
!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    IF(LDFLAG(JL)) THEN
      ZQP5(JL)=1.0_JPRB/PSP5(JL)
      ZTARG5(JL)=PT5(JL,KK)
      ZFOEEW5(JL)=R2ES*EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/(ZTARG5(JL)-Z4ES(JL)))
      ZFOEEW55B(JL)=ZFOEEW5(JL)
      ZQSAT5(JL)=ZQP5(JL)*ZFOEEW5(JL)
      LLTEST2(JL)=ZQSAT5(JL) > ZQMAX
      IF (ZQSAT5(JL) > ZQMAX) THEN
        ZQSAT5(JL)=ZQMAX
      ENDIF
      ZCOR5(JL)=1.0_JPRB/(1.0_JPRB-RETV  *ZQSAT5(JL))
      ZQSAT55D(JL)=ZQSAT5(JL)
      ZQSAT5(JL)=ZQSAT5(JL)*ZCOR5(JL)
      ZTARG55B(JL)=ZTARG5(JL)
      Z2S5(JL)=Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**2
      ZQSAT55B(JL)=ZQSAT5(JL)
      ZCOR55B(JL)=ZCOR5(JL)
      Z2S55B(JL)=Z2S5(JL)
      ZQ55B(JL)=PQ5(JL,KK)
      ZCOND5(JL)=(PQ5(JL,KK)-ZQSAT5(JL))/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      LLTEST4(JL)=ZCOND5(JL) > 0.0_JPRB
      IF (ZCOND5(JL) > 0.0_JPRB) THEN
        ZCOND5(JL)=0.0_JPRB
      ENDIF
      PT5(JL,KK)=PT5(JL,KK)+ZALDCP(JL)*ZCOND5(JL)
      PQ5(JL,KK)=PQ5(JL,KK)-ZCOND5(JL)
      IF(ZCOND5(JL) /= 0.0_JPRB) ISUM=ISUM+1
    ELSE
      ZCOND5(JL)=0.0_JPRB
    ENDIF
  ENDDO

  LLTEST5=ISUM == 0
  IF(ISUM == 0) GO TO 3315

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    LLTEST3(JL)=LDFLAG(JL).AND.ZCOND5(JL) /= 0.0_JPRB
    IF(LDFLAG(JL).AND.ZCOND5(JL) /= 0.0_JPRB) THEN
      ZTARG5(JL)=PT5(JL,KK)
      ZFOEEW5(JL)=R2ES*EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/(ZTARG5(JL)-Z4ES(JL)))
      ZFOEEW55A(JL)=ZFOEEW5(JL)
      ZQSAT5(JL)=ZQP5(JL)*ZFOEEW5(JL)
      LLTEST1(JL)=ZQSAT5(JL) > ZQMAX
      IF (ZQSAT5(JL) > ZQMAX) THEN
        ZQSAT5(JL)=ZQMAX
      ENDIF
      ZCOR5(JL)=1.0_JPRB/(1.0_JPRB-RETV  *ZQSAT5(JL))
      ZQSAT55C(JL)=ZQSAT5(JL)
      ZQSAT5(JL)=ZQSAT5(JL)*ZCOR5(JL)
      ZTARG55A(JL)=ZTARG5(JL)
      Z2S5(JL)=    Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**2
      ZQSAT55A(JL)=ZQSAT5(JL)
      ZCOR55A(JL)=ZCOR5(JL)
      Z2S55A(JL)=Z2S5(JL)
      ZQ55A(JL)=PQ5(JL,KK)
      ZCOND15(JL)=(PQ5(JL,KK)-ZQSAT5(JL))/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      PT5(JL,KK)=PT5(JL,KK)+ZALDCP(JL)*ZCOND15(JL)
      PQ5(JL,KK)=PQ5(JL,KK)-ZCOND15(JL)
    ENDIF
  ENDDO

  3315 CONTINUE

ENDIF

IF(KCALL == 0) THEN

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZQP5(JL)=1.0_JPRB/PSP5(JL)
    ZTARG5(JL)=PT5(JL,KK)
    ZFOEEW5(JL)=R2ES*EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/(ZTARG5(JL)-Z4ES(JL)))
    ZFOEEW55B(JL)=ZFOEEW5(JL)
    ZQSAT5(JL)=ZQP5(JL)*ZFOEEW5(JL)
    LLTEST2(JL)=ZQSAT5(JL) > ZQMAX
    IF (ZQSAT5(JL) > ZQMAX) THEN
      ZQSAT5(JL)=ZQMAX
    ENDIF
    ZCOR5(JL)=1.0_JPRB/(1.0_JPRB-RETV  *ZQSAT5(JL))
    ZQSAT55D(JL)=ZQSAT5(JL)
    ZQSAT5(JL)=ZQSAT5(JL)*ZCOR5(JL)
    ZTARG55B(JL)=ZTARG5(JL)
    Z2S5(JL)=    Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**2
    ZQSAT55B(JL)=ZQSAT5(JL)
    ZCOR55B(JL)=ZCOR5(JL)
    Z2S55B(JL)=Z2S5(JL)
    ZQ55B(JL)=PQ5(JL,KK)
    ZCOND15(JL)=(PQ5(JL,KK)-ZQSAT5(JL))/(1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))
    PT5(JL,KK)=PT5(JL,KK)+ZALDCP(JL)*ZCOND15(JL)
    PQ5(JL,KK)=PQ5(JL,KK)-ZCOND15(JL)
  ENDDO

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZTARG5(JL)=PT5(JL,KK)
    ZFOEEW5(JL)=R2ES*EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/(ZTARG5(JL)-Z4ES(JL)))
    ZFOEEW55A(JL)=ZFOEEW5(JL)
    ZQSAT5(JL)=ZQP5(JL)*ZFOEEW5(JL)
    LLTEST1(JL)=ZQSAT5(JL) > ZQMAX
    IF (ZQSAT5(JL) > ZQMAX) THEN
      ZQSAT5(JL)=ZQMAX
    ENDIF
    ZCOR5(JL)=1.0_JPRB/(1.0_JPRB-RETV  *ZQSAT5(JL))
    ZQSAT55C(JL)=ZQSAT5(JL)
    ZQSAT5(JL)=ZQSAT5(JL)*ZCOR5(JL)
    ZTARG55A(JL)=ZTARG5(JL)
    Z2S5(JL)=    Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**2
    ZQSAT55A(JL)=ZQSAT5(JL)
    ZCOR55A(JL)=ZCOR5(JL)
    Z2S55A(JL)=Z2S5(JL)
    ZQ55A(JL)=PQ5(JL,KK)
    ZCOND15(JL)=(PQ5(JL,KK)-ZQSAT5(JL))/(1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))
    PT5(JL,KK)=PT5(JL,KK)+ZALDCP(JL)*ZCOND15(JL)
    PQ5(JL,KK)=PQ5(JL,KK)-ZCOND15(JL)
  ENDDO

ENDIF

IF(KCALL == 4) THEN

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZQP5(JL)=1.0_JPRB/PSP5(JL)
    ZTARG5(JL)=PT5(JL,KK)
    ZFOEEW5(JL)=R2ES*EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/(ZTARG5(JL)-Z4ES(JL)))
    ZFOEEW55B(JL)=ZFOEEW5(JL)
    ZQSAT5(JL)=ZQP5(JL)*ZFOEEW5(JL)
    LLTEST2(JL)=ZQSAT5(JL) > ZQMAX
    IF (ZQSAT5(JL) > ZQMAX) THEN
      ZQSAT5(JL)=ZQMAX
    ENDIF
    ZCOR5(JL)=1.0_JPRB/(1.0_JPRB-RETV  *ZQSAT5(JL))
    ZQSAT55D(JL)=ZQSAT5(JL)
    ZQSAT5(JL)=ZQSAT5(JL)*ZCOR5(JL)
    ZTARG55B(JL)=ZTARG5(JL)
    Z2S5(JL)=    Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**2
    ZQSAT55B(JL)=ZQSAT5(JL)
    ZCOR55B(JL)=ZCOR5(JL)
    Z2S55B(JL)=Z2S5(JL)
    ZQ55B(JL)=PQ5(JL,KK)
    ZCOND5(JL)=(PQ5(JL,KK)-ZQSAT5(JL))/(1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))
    PT5(JL,KK)=PT5(JL,KK)+ZALDCP(JL)*ZCOND5(JL)
    PQ5(JL,KK)=PQ5(JL,KK)-ZCOND5(JL)
  ENDDO

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZTARG5(JL)=PT5(JL,KK)
    ZFOEEW5(JL)=R2ES*EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/(ZTARG5(JL)-Z4ES(JL)))
    ZFOEEW55A(JL)=ZFOEEW5(JL)
    ZQSAT5(JL)=ZQP5(JL)*ZFOEEW5(JL)
    LLTEST1(JL)=ZQSAT5(JL) > ZQMAX
    IF (ZQSAT5(JL) > ZQMAX) THEN
      ZQSAT5(JL)=ZQMAX
    ENDIF
    ZCOR5(JL)=1.0_JPRB/(1.0_JPRB-RETV  *ZQSAT5(JL))
    ZQSAT55C(JL)=ZQSAT5(JL)
    ZQSAT5(JL)=ZQSAT5(JL)*ZCOR5(JL)
    ZTARG55A(JL)=ZTARG5(JL)
    Z2S5(JL)=    Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**2
    ZQSAT55A(JL)=ZQSAT5(JL)
    ZCOR55A(JL)=ZCOR5(JL)
    Z2S55A(JL)=Z2S5(JL)
    ZQ55A(JL)=PQ5(JL,KK)
    ZCOND15(JL)=(PQ5(JL,KK)-ZQSAT5(JL))/(1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))
    PT5(JL,KK)=PT5(JL,KK)+ZALDCP(JL)*ZCOND15(JL)
    PQ5(JL,KK)=PQ5(JL,KK)-ZCOND15(JL)
  ENDDO

ENDIF

!----------------------------------------------------------------------

!*                 ------ ADJOINT COMPUTATIONS ------

!----------------------------------------------------------------------

!*                 INITIALISATION OF LOCAL ARRAYS

ZTARG(:) =0.0_JPRB
ZFOEEW(:)=0.0_JPRB
ZQSAT(:) =0.0_JPRB
ZCOR(:)  =0.0_JPRB
Z2S(:)   =0.0_JPRB
ZCOND1(:)=0.0_JPRB
ZCOND(:) =0.0_JPRB
ZQP(:)   =0.0_JPRB

IF(KCALL == 4) THEN

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZCOND1 (JL) = ZCOND1 (JL) - PQ (JL,KK)
    ZCOND1 (JL) = ZCOND1 (JL) + ZALDCP(JL)*PT (JL,KK)
    ZQSAT5(JL)=ZQSAT55A(JL)
    ZCOR5(JL)=ZCOR55A(JL)
    Z2S5(JL)=Z2S55A(JL)
    PQ (JL,KK) = PQ (JL,KK) + ZCOND1 (JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)*&
     & (ZQ55A(JL)-ZQSAT5(JL))*ZCOR5(JL)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    ZCOR (JL) = ZCOR (JL) - ZCOND1 (JL)*&
     & (ZQ55A(JL)-ZQSAT5(JL))*ZQSAT5(JL)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    Z2S (JL) = Z2S (JL) - ZCOND1 (JL)*&
     & (ZQ55A(JL)-ZQSAT5(JL))*ZQSAT5(JL)*ZCOR5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    ZCOND1 (JL) = 0.0_JPRB
    ZTARG5(JL)=ZTARG55A(JL)
    ZTARG(JL) = ZTARG(JL) - 2.0_JPRB*Z2S (JL)*&
     & Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**3  
    Z2S (JL) = 0.0_JPRB
    ZQSAT5(JL)=ZQSAT55C(JL)
    ZCOR (JL) = ZCOR (JL) + ZQSAT (JL)*ZQSAT5(JL)
    ZQSAT (JL) = ZQSAT (JL)*ZCOR5(JL)
    ZQSAT(JL) = ZQSAT(JL) + ZCOR(JL)*RETV/(1.0_JPRB-RETV*ZQSAT5(JL))**2
    ZCOR(JL) = 0.0_JPRB
    IF (LLTEST1(JL)) THEN
      ZQSAT (JL)=0.0_JPRB
    ENDIF
    ZFOEEW (JL) = ZFOEEW (JL) + ZQSAT (JL)*ZQP5(JL)
    ZFOEEW5(JL)=ZFOEEW55A(JL)
    ZQP (JL) = ZQP (JL) + ZQSAT (JL)*ZFOEEW5(JL)
    ZQSAT (JL) = 0.0_JPRB
    ZTARG(JL) = ZTARG(JL) + ZFOEEW (JL)*R2ES*&
     & Z3ES(JL)*(RTT-Z4ES(JL))*&
     & EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/&
     & (ZTARG5(JL)-Z4ES(JL)))/          &
     & (ZTARG5(JL)-Z4ES(JL))**2  
    ZFOEEW (JL) = 0.0_JPRB
    PT (JL,KK) = PT (JL,KK) + ZTARG (JL)
    ZTARG (JL) = 0.0_JPRB
  ENDDO

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZCOND (JL) = ZCOND (JL) - PQ (JL,KK)
    ZCOND (JL) = ZCOND (JL) + ZALDCP(JL)*PT (JL,KK)
    ZQSAT5(JL)=ZQSAT55B(JL)
    ZCOR5(JL)=ZCOR55B(JL)
    Z2S5(JL)=Z2S55B(JL)
    PQ (JL,KK) = PQ (JL,KK) + ZCOND (JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND (JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND (JL)*&
     & (ZQ55B(JL)-ZQSAT5(JL))*ZCOR5(JL)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    ZCOR (JL) = ZCOR (JL) - ZCOND (JL)*&
     & (ZQ55B(JL)-ZQSAT5(JL))*ZQSAT5(JL)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    Z2S (JL) = Z2S (JL) - ZCOND (JL)*&
     & (ZQ55B(JL)-ZQSAT5(JL))*ZQSAT5(JL)*ZCOR5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    ZCOND (JL) = 0.0_JPRB
    ZTARG5(JL)=ZTARG55B(JL)
    ZTARG(JL) = ZTARG(JL) - 2.0_JPRB*Z2S (JL)*&
     & Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**3  
    Z2S (JL) = 0.0_JPRB
    ZQSAT5(JL)=ZQSAT55D(JL)
    ZCOR (JL) = ZCOR (JL) + ZQSAT (JL)*ZQSAT5(JL)
    ZQSAT (JL) = ZQSAT (JL)*ZCOR5(JL)
    ZQSAT(JL) = ZQSAT(JL) + ZCOR(JL)*RETV/(1.0_JPRB-RETV*ZQSAT5(JL))**2
    ZCOR(JL) = 0.0_JPRB
    IF (LLTEST2(JL)) THEN
      ZQSAT (JL)=0.0_JPRB
    ENDIF
    ZFOEEW (JL) = ZFOEEW (JL) + ZQSAT (JL)*ZQP5(JL)
    ZFOEEW5(JL)=ZFOEEW55B(JL)
    ZQP (JL) = ZQP (JL) + ZQSAT (JL)*ZFOEEW5(JL)
    ZQSAT (JL) = 0.0_JPRB
    ZTARG(JL) = ZTARG(JL) + ZFOEEW (JL)*R2ES*&
     & Z3ES(JL)*(RTT-Z4ES(JL))*&
     & EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/&
     & (ZTARG5(JL)-Z4ES(JL)))/          &
     & (ZTARG5(JL)-Z4ES(JL))**2  
    ZFOEEW (JL) = 0.0_JPRB
    PT (JL,KK) = PT (JL,KK) + ZTARG (JL)
    ZTARG (JL) = 0.0_JPRB
    PSP(JL) = PSP(JL) - ZQP(JL)/PSP5(JL)**2
    ZQP(JL) = 0.0_JPRB
  ENDDO
ENDIF

IF(KCALL == 0) THEN

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZCOND1 (JL) = ZCOND1 (JL) - PQ (JL,KK)
    ZCOND1 (JL) = ZCOND1 (JL) + ZALDCP(JL)*PT (JL,KK)
    ZQSAT5(JL)=ZQSAT55A(JL)
    ZCOR5(JL)=ZCOR55A(JL)
    Z2S5(JL)=Z2S55A(JL)
    PQ (JL,KK) = PQ (JL,KK) + ZCOND1 (JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)*&
     & (ZQ55A(JL)-ZQSAT5(JL))*ZCOR5(JL)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    ZCOR (JL) = ZCOR (JL) - ZCOND1 (JL)*&
     & (ZQ55A(JL)-ZQSAT5(JL))*ZQSAT5(JL)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    Z2S (JL) = Z2S (JL) - ZCOND1 (JL)*&
     & (ZQ55A(JL)-ZQSAT5(JL))*ZQSAT5(JL)*ZCOR5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    ZCOND1 (JL) = 0.0_JPRB
    ZTARG5(JL)=ZTARG55A(JL)
    ZTARG(JL) = ZTARG(JL) - 2.0_JPRB*Z2S (JL)*&
     & Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**3  
    Z2S (JL) = 0.0_JPRB
    ZQSAT5(JL)=ZQSAT55C(JL)
    ZCOR (JL) = ZCOR (JL) + ZQSAT (JL)*ZQSAT5(JL)
    ZQSAT (JL) = ZQSAT (JL)*ZCOR5(JL)
    ZQSAT(JL) = ZQSAT(JL) + ZCOR(JL)*RETV/(1.0_JPRB-RETV*ZQSAT5(JL))**2
    ZCOR(JL) = 0.0_JPRB
    IF (LLTEST1(JL)) THEN
      ZQSAT (JL)=0.0_JPRB
    ENDIF
    ZFOEEW (JL) = ZFOEEW (JL) + ZQSAT (JL)*ZQP5(JL)
    ZFOEEW5(JL)=ZFOEEW55A(JL)
    ZQP (JL) = ZQP (JL) + ZQSAT (JL)*ZFOEEW5(JL)
    ZQSAT (JL) = 0.0_JPRB
    ZTARG(JL) = ZTARG(JL) + ZFOEEW (JL)*R2ES*&
     & Z3ES(JL)*(RTT-Z4ES(JL))*&
     & EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/&
     & (ZTARG5(JL)-Z4ES(JL)))/          &
     & (ZTARG5(JL)-Z4ES(JL))**2  
    ZFOEEW (JL) = 0.0_JPRB
    PT (JL,KK) = PT (JL,KK) + ZTARG (JL)
    ZTARG (JL) = 0.0_JPRB
  ENDDO

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZCOND1 (JL) = ZCOND1 (JL) - PQ (JL,KK)
    ZCOND1 (JL) = ZCOND1 (JL) + ZALDCP(JL)*PT (JL,KK)
    ZQSAT5(JL)=ZQSAT55B(JL)
    ZCOR5(JL)=ZCOR55B(JL)
    Z2S5(JL)=Z2S55B(JL)
    PQ (JL,KK) = PQ (JL,KK) + ZCOND1 (JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)*&
     & (ZQ55B(JL)-ZQSAT5(JL))*ZCOR5(JL)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    ZCOR (JL) = ZCOR (JL) - ZCOND1 (JL)*&
     & (ZQ55B(JL)-ZQSAT5(JL))*ZQSAT5(JL)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    Z2S (JL) = Z2S (JL) - ZCOND1 (JL)*&
     & (ZQ55B(JL)-ZQSAT5(JL))*ZQSAT5(JL)*ZCOR5(JL)/&
     & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
    ZCOND1 (JL) = 0.0_JPRB
    ZTARG5(JL)=ZTARG55B(JL)
    ZTARG(JL) = ZTARG(JL) - 2.0_JPRB*Z2S (JL)*&
     & Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**3  
    Z2S (JL) = 0.0_JPRB
    ZQSAT5(JL)=ZQSAT55D(JL)
    ZCOR (JL) = ZCOR (JL) + ZQSAT (JL)*ZQSAT5(JL)
    ZQSAT (JL) = ZQSAT (JL)*ZCOR5(JL)
    ZQSAT(JL) = ZQSAT(JL) + ZCOR(JL)*RETV/(1.0_JPRB-RETV*ZQSAT5(JL))**2
    ZCOR(JL) = 0.0_JPRB
    IF (LLTEST2(JL)) THEN
      ZQSAT (JL)=0.0_JPRB
    ENDIF
    ZFOEEW (JL) = ZFOEEW (JL) + ZQSAT (JL)*ZQP5(JL)
    ZFOEEW5(JL)=ZFOEEW55B(JL)
    ZQP (JL) = ZQP (JL) + ZQSAT (JL)*ZFOEEW5(JL)
    ZQSAT (JL) = 0.0_JPRB
    ZTARG(JL) = ZTARG(JL) + ZFOEEW (JL)*R2ES*&
     & Z3ES(JL)*(RTT-Z4ES(JL))*&
     & EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/&
     & (ZTARG5(JL)-Z4ES(JL)))/          &
     & (ZTARG5(JL)-Z4ES(JL))**2  
    ZFOEEW (JL) = 0.0_JPRB
    PT (JL,KK) = PT (JL,KK) + ZTARG (JL)
    ZTARG (JL) = 0.0_JPRB
    PSP(JL) = PSP(JL) - ZQP(JL)/PSP5(JL)**2
    ZQP(JL) = 0.0_JPRB
  ENDDO
ENDIF

IF(KCALL == 2) THEN

  IF(LLTEST5) GO TO 331

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    IF(LLTEST3(JL)) THEN
      ZCOND1 (JL) = ZCOND1 (JL) - PQ (JL,KK)
      ZCOND1 (JL) = ZCOND1 (JL) + ZALDCP(JL)*PT (JL,KK)
      ZQSAT5(JL)=ZQSAT55A(JL)
      ZCOR5(JL)=ZCOR55A(JL)
      Z2S5(JL)=Z2S55A(JL)
      PQ (JL,KK) = PQ (JL,KK) + ZCOND1 (JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)*&
       & (ZQ55A(JL)-ZQSAT5(JL))*ZCOR5(JL)*Z2S5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      ZCOR (JL) = ZCOR (JL) - ZCOND1 (JL)*&
       & (ZQ55A(JL)-ZQSAT5(JL))*ZQSAT5(JL)*Z2S5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      Z2S (JL) = Z2S (JL) - ZCOND1 (JL)*&
       & (ZQ55A(JL)-ZQSAT5(JL))*ZQSAT5(JL)*ZCOR5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      ZCOND1 (JL) = 0.0_JPRB
      ZTARG5(JL)=ZTARG55A(JL)
      ZTARG(JL) = ZTARG(JL) - 2.0_JPRB*Z2S (JL)*&
       & Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**3  
      Z2S (JL) = 0.0_JPRB
      ZQSAT5(JL)=ZQSAT55C(JL)
      ZCOR (JL) = ZCOR (JL) + ZQSAT (JL)*ZQSAT5(JL)
      ZQSAT (JL) = ZQSAT (JL)*ZCOR5(JL)
      ZQSAT(JL) = ZQSAT(JL) + ZCOR(JL)*RETV/(1.0_JPRB-RETV*ZQSAT5(JL))**2
      ZCOR(JL) = 0.0_JPRB
      IF (LLTEST1(JL)) THEN
        ZQSAT (JL)=0.0_JPRB
      ENDIF
      ZFOEEW (JL) = ZFOEEW (JL) + ZQSAT (JL)*ZQP5(JL)
      ZFOEEW5(JL)=ZFOEEW55A(JL)
      ZQP (JL) = ZQP (JL) + ZQSAT (JL)*ZFOEEW5(JL)
      ZQSAT (JL) = 0.0_JPRB
      ZTARG(JL) = ZTARG(JL) + ZFOEEW (JL)*R2ES*&
       & Z3ES(JL)*(RTT-Z4ES(JL))*&
       & EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/&
       & (ZTARG5(JL)-Z4ES(JL)))/          &
       & (ZTARG5(JL)-Z4ES(JL))**2  
      ZFOEEW (JL) = 0.0_JPRB
      PT (JL,KK) = PT (JL,KK) + ZTARG (JL)
      ZTARG (JL) = 0.0_JPRB
    ENDIF
  ENDDO
!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    IF(LDFLAG(JL)) THEN
      ZCOND (JL) = ZCOND (JL) - PQ (JL,KK)
      ZCOND (JL) = ZCOND (JL) + ZALDCP(JL)*PT (JL,KK)
      ZQSAT5(JL)=ZQSAT55B(JL)
      ZCOR5(JL)=ZCOR55B(JL)
      Z2S5(JL)=Z2S55B(JL)
      IF (LLTEST4(JL)) THEN
        ZCOND (JL)=0.0_JPRB
      ENDIF
      PQ (JL,KK) = PQ (JL,KK) + ZCOND (JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      ZQSAT (JL) = ZQSAT (JL) - ZCOND (JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      ZQSAT (JL) = ZQSAT (JL) - ZCOND (JL)*&
       & (ZQ55B(JL)-ZQSAT5(JL))*ZCOR5(JL)*Z2S5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      ZCOR (JL) = ZCOR (JL) - ZCOND (JL)*&
       & (ZQ55B(JL)-ZQSAT5(JL))*ZQSAT5(JL)*Z2S5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      Z2S (JL) = Z2S (JL) - ZCOND (JL)*&
       & (ZQ55B(JL)-ZQSAT5(JL))*ZQSAT5(JL)*ZCOR5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      ZCOND (JL) = 0.0_JPRB
      ZTARG5(JL)=ZTARG55B(JL)
      ZTARG(JL) = ZTARG(JL) - 2.0_JPRB*Z2S (JL)*&
       & Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**3  
      Z2S (JL) = 0.0_JPRB
      ZQSAT5(JL)=ZQSAT55D(JL)
      ZCOR (JL) = ZCOR (JL) + ZQSAT (JL)*ZQSAT5(JL)
      ZQSAT (JL) = ZQSAT (JL)*ZCOR5(JL)
      ZQSAT(JL) = ZQSAT(JL) + ZCOR(JL)*RETV/(1.0_JPRB-RETV*ZQSAT5(JL))**2
      ZCOR(JL) = 0.0_JPRB
      IF (LLTEST2(JL)) THEN
        ZQSAT (JL)=0.0_JPRB
      ENDIF
      ZFOEEW (JL) = ZFOEEW (JL) + ZQSAT (JL)*ZQP5(JL)
      ZFOEEW5(JL)=ZFOEEW55B(JL)
      ZQP (JL) = ZQP (JL) + ZQSAT (JL)*ZFOEEW5(JL)
      ZQSAT (JL) = 0.0_JPRB
      ZTARG(JL) = ZTARG(JL) + ZFOEEW (JL)*R2ES*&
       & Z3ES(JL)*(RTT-Z4ES(JL))*&
       & EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/&
       & (ZTARG5(JL)-Z4ES(JL)))/          &
       & (ZTARG5(JL)-Z4ES(JL))**2  
      ZFOEEW (JL) = 0.0_JPRB
      PT (JL,KK) = PT (JL,KK) + ZTARG (JL)
      ZTARG (JL) = 0.0_JPRB
      PSP(JL) = PSP(JL) - ZQP(JL)/PSP5(JL)**2
      ZQP(JL) = 0.0_JPRB
    ELSE
      ZCOND (JL)=0.0_JPRB
    ENDIF
  ENDDO
  331 CONTINUE

ENDIF
IF (KCALL == 1 ) THEN

  IF(LLTEST6) GO TO 231

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    IF(LLTEST3(JL)) THEN
      ZCOND1 (JL) = ZCOND1 (JL) - PQ (JL,KK)
      ZCOND1 (JL) = ZCOND1 (JL) + ZALDCP(JL)*PT (JL,KK)
      ZQSAT5(JL)=ZQSAT55A(JL)
      ZCOR5(JL)=ZCOR55A(JL)
      Z2S5(JL)=Z2S55A(JL)
      PQ (JL,KK) = PQ (JL,KK) + ZCOND1 (JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)*&
       & (ZQ55A(JL)-ZQSAT5(JL))*ZCOR5(JL)*Z2S5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      ZCOR (JL) = ZCOR (JL) - ZCOND1 (JL)*&
       & (ZQ55A(JL)-ZQSAT5(JL))*ZQSAT5(JL)*Z2S5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      Z2S (JL) = Z2S (JL) - ZCOND1 (JL)*&
       & (ZQ55A(JL)-ZQSAT5(JL))*ZQSAT5(JL)*ZCOR5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      ZCOND1 (JL) = 0.0_JPRB
      ZTARG5(JL)=ZTARG55A(JL)
      ZTARG(JL) = ZTARG(JL) - 2.0_JPRB*Z2S (JL)*&
       & Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**3  
      Z2S (JL) = 0.0_JPRB
      ZQSAT5(JL)=ZQSAT55C(JL)
      ZCOR (JL) = ZCOR (JL) + ZQSAT (JL)*ZQSAT5(JL)
      ZQSAT (JL) = ZQSAT (JL)*ZCOR5(JL)
      ZQSAT(JL) = ZQSAT(JL) + ZCOR(JL)*RETV/(1.0_JPRB-RETV*ZQSAT5(JL))**2
      ZCOR(JL) = 0.0_JPRB
      IF (LLTEST1(JL)) THEN
        ZQSAT (JL)=0.0_JPRB
      ENDIF
      ZFOEEW (JL) = ZFOEEW (JL) + ZQSAT (JL)*ZQP5(JL)
      ZFOEEW5(JL)=ZFOEEW55A(JL)
      ZQP (JL) = ZQP (JL) + ZQSAT (JL)*ZFOEEW5(JL)
      ZQSAT (JL) = 0.0_JPRB
      ZTARG(JL) = ZTARG(JL) + ZFOEEW (JL)*R2ES*&
       & Z3ES(JL)*(RTT-Z4ES(JL))*&
       & EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/&
       & (ZTARG5(JL)-Z4ES(JL)))/          &
       & (ZTARG5(JL)-Z4ES(JL))**2  
      ZFOEEW (JL) = 0.0_JPRB
      PT (JL,KK) = PT (JL,KK) + ZTARG (JL)
      ZTARG (JL) = 0.0_JPRB
    ENDIF
  ENDDO

  231 CONTINUE

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    IF(LDFLAG(JL)) THEN
      ZCOND (JL) = ZCOND (JL) - PQ (JL,KK)
      ZCOND (JL) = ZCOND (JL) + ZALDCP(JL)*PT (JL,KK)
      ZQSAT5(JL)=ZQSAT55B(JL)
      ZCOR5(JL)=ZCOR55B(JL)
      Z2S5(JL)=Z2S55B(JL)
      IF (LLTEST4(JL)) THEN
        ZCOND (JL)=0.0_JPRB
      ENDIF
      PQ (JL,KK) = PQ (JL,KK) + ZCOND (JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      ZQSAT (JL) = ZQSAT (JL) - ZCOND (JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))  
      ZQSAT (JL) = ZQSAT (JL) - ZCOND (JL)*&
       & (ZQ55B(JL)-ZQSAT5(JL))*ZCOR5(JL)*Z2S5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      ZCOR (JL) = ZCOR (JL) - ZCOND (JL)*&
       & (ZQ55B(JL)-ZQSAT5(JL))*ZQSAT5(JL)*Z2S5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      Z2S (JL) = Z2S (JL) - ZCOND (JL)*&
       & (ZQ55B(JL)-ZQSAT5(JL))*ZQSAT5(JL)*ZCOR5(JL)/&
       & (1.0_JPRB+ZQSAT5(JL)*ZCOR5(JL)*Z2S5(JL))**2  
      ZCOND (JL) = 0.0_JPRB
      ZTARG5(JL)=ZTARG55B(JL)
      ZTARG(JL) = ZTARG(JL) - 2.0_JPRB*Z2S (JL)*&
       & Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**3  
      Z2S (JL) = 0.0_JPRB
      ZQSAT5(JL)=ZQSAT55D(JL)
      ZCOR (JL) = ZCOR (JL) + ZQSAT (JL)*ZQSAT5(JL)
      ZQSAT (JL) = ZQSAT (JL)*ZCOR5(JL)
      ZQSAT(JL) = ZQSAT(JL) + ZCOR(JL)*RETV/(1.0_JPRB-RETV*ZQSAT5(JL))**2
      ZCOR(JL) = 0.0_JPRB
      IF (LLTEST2(JL)) THEN
        ZQSAT (JL)=0.0_JPRB
      ENDIF
      ZFOEEW (JL) = ZFOEEW (JL) + ZQSAT (JL)*ZQP5(JL)
      ZFOEEW5(JL)=ZFOEEW55B(JL)
      ZQP (JL) = ZQP (JL) + ZQSAT (JL)*ZFOEEW5(JL)
      ZQSAT (JL) = 0.0_JPRB
      ZTARG(JL) = ZTARG(JL) + ZFOEEW (JL)*R2ES*&
       & Z3ES(JL)*(RTT-Z4ES(JL))*&
       & EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/&
       & (ZTARG5(JL)-Z4ES(JL)))/          &
       & (ZTARG5(JL)-Z4ES(JL))**2  
      ZFOEEW (JL) = 0.0_JPRB
      PT (JL,KK) = PT (JL,KK) + ZTARG (JL)
      ZTARG (JL) = 0.0_JPRB
      PSP(JL) = PSP(JL) - ZQP(JL)/PSP5(JL)**2
      ZQP(JL) = 0.0_JPRB
    ELSE
      ZCOND (JL)=0.0_JPRB
    ENDIF
  ENDDO

ENDIF

!IF (LHOOK) CALL DR_HOOK('CUADJTQSAD',1,ZHOOK_HANDLE)
END SUBROUTINE CUADJTQSAD
