MODULE ERROR_MOD
  USE PARKIND1, ONLY: JPIM, JPRB
  IMPLICIT NONE
  CONTAINS
  SUBROUTINE ERROR_NORM(NLON, FIELD, PERT5, PERT, ZNORM, ZCOUNT, ZLAMBDA)
    INTEGER(KIND=JPIM), INTENT(IN) :: NLON
    REAL(KIND=JPRB), INTENT(IN) :: FIELD(:,:), PERT5(:,:), PERT(:,:)
    REAL(KIND=JPRB), INTENT(IN) :: ZLAMBDA
    REAL(KIND=JPRB), INTENT(INOUT) :: ZNORM, ZCOUNT

    IF (ABS(SUM(PERT(1:NLON,:)*ZLAMBDA)) > EPSILON(ZLAMBDA) ) THEN
      ZCOUNT = ZCOUNT + 1._JPRB
      ZNORM = ZNORM + ABS(SUM(FIELD(1:NLON,:)-PERT5(1:NLON,:)) / SUM(PERT(1:NLON,:)*ZLAMBDA))
    END IF
  END SUBROUTINE ERROR_NORM
END MODULE ERROR_MOD

