! Copyright (C) 2003- ECMWF
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
!
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!l
MODULE CLOUDSC2AD_MOD

CONTAINS
SUBROUTINE CLOUDSC2AD ( &
 & KIDIA , KFDIA , KLON , KTDIA , KLEV, LDRAIN1D,&
 & PTSPHY, CETA,&
 & PAPHP15 , PAPP15  , PQM15   , PQS5   , PTM15,  PL5 ,  PI5,&
 & PLUDE5  , PLU5    , PMFU5   , PMFD5,&
 & PTENT5  , PGTENT5 , PTENQ5  , PGTENQ5,&
 & PTENL5  , PGTENL5 , PTENI5  , PGTENI5, PSUPSAT5, &
 & PCLC5   , PFPLSL5 , PFPLSN5,&
 & PFHPSL5 , PFHPSN5 , PCOVPTOT5,&
 & PAPHP1 ,  PAPP1   , PQM1   , PQS   , PTM1,  PL ,  PI,&
 & PLUDE  , PLU      , PMFU   , PMFD,&
 & PTENT  , PGTENT , PTENQ , PGTENQ,&
 & PTENL  , PGTENL , PTENI , PGTENI, PSUPSAT,&
 & PCLC   , PFPLSL , PFPLSN,&
 & PFHPSL , PFHPSN , PCOVPTOT,&
 & YDCST, YDTHF, YHNC, YPHLI, YCLD, YCLDP, YNCL)

!**** *CLOUDSC2AD*  - COMPUTES CLOUD COVER, CLOUD LIQUID WATER/ICE
!                     AND LARGE-SCALE CONDENSATION.
!                     PROGNOSTIC CLOUD LIQUID WATER/ICE VARIABLES.
!                     (adjoint)

!     PURPOSE.
!     --------
!         THIS ROUTINE COMPUTES CLOUD AMOUNTS WHICH ARE REQUIRED BY THE
!     RADIATION SCHEME FOR COMPUTATION OF THE FLUXES AND HE PHYSICAL
!     TENDENCIES OF THE TWO PROGNOSTIC VARIABLES T AND Q DUE TO
!     THE WATER PHASE CHANGES

!**   INTERFACE.
!     ----------
!              *CLOUDSC2AD* IS CALLED FROM *CALLPARAD*

!     PARAMETER     DESCRIPTION                                   UNITS
!     ---------     -----------                                   -----

!     INPUT PARAMETERS (INTEGER):

!    *KIDIA*        START POINT
!    *KFDIA*        END POINT
!    *KLON*         NUMBER OF GRID POINTS PER PACKET
!    *KTDIA*        START OF THE VERTICAL LOOP
!    *KLEV*         NUMBER OF LEVELS

!    INPUT PARAMETERS (REAL):

!    *PTSPHY*       TIME STEP FOR THE PHYSICS                     S
!    *PQM15*        SPECIFIC HUMIDITY AT T-1                  (Trajectory)
!    *PQS5*         SATURATION SPECIFIC HUMIDITY              (Trajectory)
!    *PTM15*        TEMPERATURE AT T-1                        (Trajectory)
!    *PL5*          CLOUD LIQUID WATER                        (Trajectory) 
!    *PI5*          CLOUD ICE                                 (Trajectory)  
!    *PAPP15*       PROVISIONAL PRESSURE ON FULL LEVELS       (Trajectory)
!    *PAPHP15*      PRESSURE AT HALF LEVELS AT T-1            (Trajectory)
!    *PLUDE5*       DETRAINED LIQUID WATER                    (Trajectory)
!    *PLU5*         LIQUID WATER CONTENT IN UPDRAFTS          (Trajectory)
!    *PMFU5*        MASS FLUX IN CONVECTIVE UPDRAFTS          (Trajectory)
!    *PMFD5*        MASS FLUX IN CONVECTIVE DOWNDRAFTS         (Trajectory)

!    *PQM1*         SPECIFIC HUMIDITY AT T-1                     KG/KG
!    *PQS*          SATURATION SPECIFIC HUMIDITY                 KG/KG
!    *PTM1*         TEMPERATURE AT T-1                             K
!    *PL*           CLOUD LIQUID WATER                           KG/KG       
!    *PI*           CLOUD ICE                                    KG/KG       
!    *PAPHP1*       PRESSURE AT HALF LEVELS AT T-1                PA   
!    *PAPP1*        PROVISIONAL PRESSURE ON FULL LEVELS           PA
!    *PLUDE*        DETRAINED LIQUID WATER                       KG/(M3*S)
!    *PLU*          LIQUID WATER CONTENT IN UPDRAFTS             KG/KG
!    *PMFU*         MASS FLUX IN CONVECTIVE UPDRAFTS             KG/(M2*S)
!    *PMFD*         MASS FLUX IN CONVECTIVE DOWNDRAFTS           KG/(M2*S)

!    UPDATED PARAMETERS (REAL):
!    *PTENT5*       TEMPERATURE TENDENCY                      (Trajectory)
!    *PTENQ5*       MOISTURE TENDENCY                         (Trajectory)
!    *PTENL5*       CLOUD LIQUID WATER TENDENCY               (Trajectory)
!    *PTENI5*       CLOUD ICE TENDENCY                        (Trajectory)

!    *PTENT*        TEMPERATURE TENDENCY                          K/S
!    *PTENQ*        MOISTURE TENDENCY                            KG/(KG S)
!    *PTENL*        CLOUD LIQUID WATER TENDENCY                  KG/(KG S)      
!    *PTENI*        CLOUD ICE  TENDENCY                          KG/(KG S)      

!    OUTPUT PARAMETERS (REAL):

!    *PCLC5*        CLOUD COVER OF INDIVIDUAL LAYER
!    *PFHPSL5*      ENTHALPY FLUX DUE TO LARGE SCALE RAIN     (Trajectory) 
!    *PFHPSN5*      ENTHALPY FLUX DUE TO LARGE SCALE SNOW     (Trajectory) 
!    *PFPLSL5*      LARGE SCALE RAIN FLUX                     (Trajectory)
!    *PFPLSN5*      LARGE SCALE SNOW FLUX                     (Trajectory)  
!    *PCOVPTOT5*    PRECIPITATION FRACTION IN EACH LAYER      (Trajectory)  

!    *PCLC*         CLOUD COVER OF INDIVIDUAL LAYER
!    *PFHPSL*       ENTHALPY FLUX DUE TO LARGE SCALE RAIN         J/(M2*S)
!    *PFHPSN*       ENTHALPY FLUX DUE TO LARGE SCALE SNOW         J/(M2*S)
!    *PFPLSL*       LARGE SCALE RAIN FLUX                        KG/(M2*S)
!    *PFPLSN*       LARGE SCALE SNOW FLUX                        KG/(M2*S)
!    *PCOVPTOT*     PRECIPITATION FRACTION IN EACH LAYER

!     METHOD.
!     -------

!     EXTERNALS.
!     ----------

!          NONE

!     REFERENCE.
!     ----------

!     AUTHOR.
!     -------
!     2010-03-25  P. Lopez, ECMWF

!     MODIFICATIONS.
!     --------------
!     F. Vana 01-Sep-2020  Introduced to CY46R1
!-----------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
!USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK

USE YOMNCL   , ONLY : TNCL
USE YOMCST   , ONLY : TOMCST
USE YOETHF   , ONLY : TOETHF
USE YOPHNC   , ONLY : TPHNC
USE YOEPHLI  , ONLY : TEPHLI
USE YOECLD   , ONLY : TECLD
USE YOECLDP  , ONLY : TECLDP

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KTDIA 
LOGICAL           ,INTENT(IN)    :: LDRAIN1D
REAL(KIND=JPRB)   , INTENT(IN)   :: CETA(KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSPHY 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPHP15(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPP15(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQM15(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQS5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTM15(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PL5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PI5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLUDE5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLU5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMFU5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMFD5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENT5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENQ5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENL5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENI5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGTENT5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGTENQ5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGTENL5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGTENI5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSUPSAT5(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCLC5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFPLSL5(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFPLSN5(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFHPSL5(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFHPSN5(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCOVPTOT5(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PAPHP1(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PAPP1(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PQM1(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PQS(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTM1(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PLUDE(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PL(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PI(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PLU(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PMFU(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PMFD(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENT(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENQ(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENL(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTENI(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGTENT(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGTENQ(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGTENL(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGTENI(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSUPSAT(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PCLC(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPLSL(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPLSN(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFHPSL(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFHPSN(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PCOVPTOT(KLON,KLEV) 
!     -----------------------------------------------------------------

!*       0.1   ARGUMENTS.
!              ----------

!     -----------------------------------------------------------------

!*       0.2   LOCAL ARRAYS.
!              -------------

INTEGER(KIND=JPIM) :: JK, JL

!=======================================================================
!     TUNABLE CONSTANTS (to be moved to include files later)
!=======================================================================

! zscal is a scale factor that linearly reduces the variance between 
! qv=qv-crit and qv-qsat
! 0 = No scaling
! 1 = full scaling (i.e. variance=0 when qv=qsat)

REAL(KIND=JPRB) :: ZSCAL=0.9_JPRB

!=======================================================================

REAL(KIND=JPRB) :: ZTP15(KLON,KLEV), ZQP15(KLON,KLEV)
REAL(KIND=JPRB) :: ZL5(KLON,KLEV), ZI5(KLON,KLEV)
REAL(KIND=JPRB) :: ZLUDE5(KLON,KLEV), ZQLWC5(KLON,KLEV), ZQIWC5(KLON,KLEV)
REAL(KIND=JPRB) :: ZDP5(KLON,KLEV)
REAL(KIND=JPRB) :: ZLSDCP5(KLON,KLEV), ZLFDCP5(KLON,KLEV), ZLVDCP5(KLON,KLEV)
REAL(KIND=JPRB) :: ZFWATR15(KLON,KLEV), ZFWATR25(KLON,KLEV)
REAL(KIND=JPRB) :: ZRFREEZE15(KLON,KLEV), ZRFREEZE35(KLON,KLEV)
REAL(KIND=JPRB) :: ZQT5(KLON,KLEV)
REAL(KIND=JPRB) :: ZQC15(KLON,KLEV), ZQC25(KLON,KLEV), ZQC35(KLON,KLEV)
REAL(KIND=JPRB) :: ZRHO5(KLON,KLEV), ZRODQSDP5(KLON,KLEV), ZLDCP5(KLON,KLEV)
REAL(KIND=JPRB) :: DTDZMO5(KLON,KLEV), ZDQSDZ5(KLON,KLEV) 
REAL(KIND=JPRB) :: ZCONDL15(KLON,KLEV), ZCONDL25(KLON,KLEV) 
REAL(KIND=JPRB) :: ZCONDI15(KLON,KLEV), ZCONDI25(KLON,KLEV) 
REAL(KIND=JPRB) :: ZEVAPR5(KLON,KLEV), ZEVAPS5(KLON,KLEV) 
REAL(KIND=JPRB) :: ZQSAT5(KLON,KLEV), ZSUPSAT5(KLON,KLEV)
REAL(KIND=JPRB) :: ZQSAT5T(KLON,KLEV)

REAL(KIND=JPRB) :: ZTP1(KLON,KLEV), ZQP1(KLON,KLEV)
REAL(KIND=JPRB) :: ZL(KLON,KLEV), ZI(KLON,KLEV)
REAL(KIND=JPRB) :: ZLUDE(KLON,KLEV), ZQLWC(KLON,KLEV), ZQIWC(KLON,KLEV)
REAL(KIND=JPRB) :: ZRFL(KLON), ZSFL(KLON)
REAL(KIND=JPRB) :: ZDP(KLON,KLEV)
REAL(KIND=JPRB) :: ZLSDCP(KLON,KLEV), ZLFDCP(KLON,KLEV), ZLVDCP(KLON,KLEV)
REAL(KIND=JPRB) :: ZRFLN(KLON), ZSFLN(KLON), ZGDP(KLON)
REAL(KIND=JPRB) :: ZRFREEZE(KLON,KLEV)
REAL(KIND=JPRB) :: ZQCRIT(KLON) , ZCOVPTOT(KLON), ZCOVPCLR(KLON)
REAL(KIND=JPRB) :: ZDQSDTEMP(KLON), ZCORQS(KLON), ZDTGDP(KLON)
REAL(KIND=JPRB) :: ZQOLD(KLON), ZPP(KLON), ZDQ(KLON), ZQLIM(KLON), ZQC(KLON)
REAL(KIND=JPRB) :: ZQC1(KLON,KLEV), ZCONDL(KLON,KLEV), ZCONDI(KLON,KLEV)
REAL(KIND=JPRB) :: ZEVAPR(KLON,KLEV), ZEVAPS(KLON,KLEV) 
REAL(KIND=JPRB) :: ZQSAT(KLON), ZFWAT(KLON), ZFOEEW(KLON), ZFOEEW55B(KLON) 

REAL(KIND=JPRB) :: ZCRH(KLEV), ZSCALM(KLEV)

REAL(KIND=JPRB) :: ZZZ5(KLON,KLEV), ZCLDL5(KLON,KLEV), ZCLDI5(KLON,KLEV)
REAL(KIND=JPRB) :: ZPRR5(KLON,KLEV), ZPRS5(KLON,KLEV)
REAL(KIND=JPRB) :: ZDL5(KLON,KLEV), ZDI5(KLON,KLEV)
REAL(KIND=JPRB) :: ZCONS5(KLON,KLEV), ZSNMLT5(KLON,KLEV), ZZ2S5(KLON,KLEV)
REAL(KIND=JPRB) :: ZRFLN5(KLON), ZSFLN5(KLON)
REAL(KIND=JPRB) :: ZGDP5(KLON,KLEV)
REAL(KIND=JPRB) :: ZQCRIT5(KLON,KLEV)
REAL(KIND=JPRB) :: ZDR15(KLON,KLEV), ZDR25(KLON,KLEV)
REAL(KIND=JPRB) :: ZTP25(KLON,KLEV), ZTP35(KLON,KLEV),ZQP25(KLON,KLEV)
REAL(KIND=JPRB) :: ZTPB5(KLON,KLEV), ZQPB5(KLON,KLEV)
REAL(KIND=JPRB) :: ZQLWC15(KLON,KLEV), ZQIWC15(KLON,KLEV), ZCLC5(KLON,KLEV)
REAL(KIND=JPRB) :: ZEXP15(KLON,KLEV), ZEXP25(KLON,KLEV), ZEXP35(KLON,KLEV)
REAL(KIND=JPRB) :: ZEXPDL5(KLON,KLEV), ZEXPDI5(KLON,KLEV)

REAL(KIND=JPRB) :: ZOEALFAW5(KLON,KLEV), ZFWAT5(KLON,KLEV)
REAL(KIND=JPRB) :: ZCOVPTOT15(KLON,KLEV), ZFOEEW5(KLON,KLEV)
REAL(KIND=JPRB) :: ZFOEEW5T(KLON,KLEV)
REAL(KIND=JPRB) :: ZCOVPCLR5(KLON,KLEV), ZCOVPCLR15(KLON,KLEV)
REAL(KIND=JPRB) :: ZESDP5(KLON,KLEV), ZESDP15(KLON,KLEV), ZFAC5(KLON,KLEV)
REAL(KIND=JPRB) :: ZFACW5(KLON,KLEV), ZFACI5(KLON,KLEV), ZCOR5(KLON,KLEV)
REAL(KIND=JPRB) :: ZCOR5T(KLON,KLEV)
REAL(KIND=JPRB) :: ZDQSDTEMP5(KLON,KLEV), ZCORQS5(KLON,KLEV)
REAL(KIND=JPRB) :: ZPRTOT5(KLON,KLEV), ZQE5 (KLON,KLEV), ZB5(KLON,KLEV)
REAL(KIND=JPRB) :: ZPRECLR5(KLON,KLEV), ZPRECLR15(KLON,KLEV) 
REAL(KIND=JPRB) :: ZBETA5(KLON,KLEV), ZDTGDP5(KLON,KLEV)  
REAL(KIND=JPRB) :: ZDPR5(KLON,KLEV), ZDPR15(KLON,KLEV)
REAL(KIND=JPRB) :: ZRFLN25(KLON,KLEV), ZSFLN25(KLON,KLEV)
REAL(KIND=JPRB) :: ZQOLD5(KLON,KLEV)
REAL(KIND=JPRB) :: ZPP5(KLON)
REAL(KIND=JPRB) :: ZDQ5(KLON,KLEV), ZQLIM5(KLON,KLEV)
REAL(KIND=JPRB) :: ZQPD5(KLON,KLEV), ZQCD5(KLON,KLEV)
REAL(KIND=JPRB) :: ZSQRT5(KLON,KLEV), ZDQC5(KLON,KLEV)
REAL(KIND=JPRB) :: ZRFL5(KLON,KLEV+1), ZSFL5(KLON,KLEV+1)
REAL(KIND=JPRB) :: ZFAC1(KLON,KLEV), ZFAC2(KLON,KLEV)
REAL(KIND=JPRB) :: ZFAC3(KLON,KLEV), ZFAC4(KLON,KLEV)
REAL(KIND=JPRB) :: ZCRH2(KLON,KLEV)
REAL(KIND=JPRB) :: ZCOVPTOT5(KLON,0:KLEV)

REAL(KIND=JPRB) :: ZDQDT5, ZDTDT5, ZDLDT5, ZDIDT5
REAL(KIND=JPRB) :: ZLNEW5, ZINEW5, ZRN5, ZSN5, ZXX5, ZOEALFA5, ZRFREEZE25

REAL(KIND=JPRB) :: ZDQDT , ZDTDT , ZDLDT , ZDIDT 
REAL(KIND=JPRB) :: ZRHO, ZRODQSDP, ZLDCP, DTDZMO, ZDQSDZ, ZQT, ZSUPSAT, ZDR, ZDR2

REAL(KIND=JPRB) :: ZOEALFA, ZCLDL, ZCLDI, ZLNEW, ZINEW, ZPRR, ZPRS
REAL(KIND=JPRB) :: ZLCRIT, ZDL, ZDI, ZZ2S
REAL(KIND=JPRB) :: ZCONS, ZSNMLT, ZZZ, ZRN, ZSN
REAL(KIND=JPRB) :: ZOEALFAW, ZFAC, ZFACW, ZFACI, ZESDP
REAL(KIND=JPRB) :: ZPRTOT, ZDPR, ZPRECLR
REAL(KIND=JPRB) :: ZQE, ZBETA, ZB, ZQPD, ZQCD, ZFWATR, ZRFREEZE2, ZDQC

REAL(KIND=JPRB) :: ZCKCODTL, ZCKCODTI, ZCONS2, ZCONS3, ZMELTP2
REAL(KIND=JPRB) :: Z3ES(KLON), Z4ES(KLON)
REAL(KIND=JPRB) :: Z2S(KLON), ZCOND1(KLON)
REAL(KIND=JPRB) :: ZTARG(KLON), ZQP(KLON), ZQP5(KLON), ZTARG5(KLON)
REAL(KIND=JPRB) :: ZALDCP(KLON), Z5ALCP(KLON)
REAL(KIND=JPRB) :: ZCOR(KLON), ZCOND(KLON)
REAL(KIND=JPRB) :: ZQMAX, ZQTMST
REAL(KIND=JPRB) ::     ZQSAT55C(KLON),         ZCOR55A(KLON),&
 & Z2S55A(KLON),           ZTARG55A(KLON),&
 & ZQSAT55A(KLON),         ZFOEEW55A(KLON),&
 & ZQSAT55D(KLON),         ZCOR55B(KLON),&
 & Z2S55B(KLON),           ZTARG55B(KLON),&
 & ZQSAT55B(KLON),         Z2S5(KLON), ZCOND15(KLON), &
 & ZQ55A(KLON),            ZQ55B(KLON)
LOGICAL ::  LLTEST1(KLON),          LLTEST2(KLON)

REAL(KIND=JPRB) :: ZRH1,ZRH2,ZRH3,ZETA2,ZDETA1,ZDETA2 
REAL(KIND=JPRB) :: ZTRPAUS(KLON)
REAL(KIND=JPRB) :: ZETA3

REAL(KIND=JPRB) :: ZEPS1,ZEPS2,ZCKCODTLA,ZCKCODTIA

REAL(KIND=JPRB) :: ZYYY, ZRAT


LOGICAL :: LLO1, LLO2
LOGICAL :: LLFLAG(KLEV)
LOGICAL :: LLO3(KLON,KLEV)
TYPE(TOMCST)      ,INTENT(IN) :: YDCST
TYPE(TOETHF)      ,INTENT(IN) :: YDTHF
TYPE(TPHNC)       ,INTENT(IN) :: YHNC
TYPE(TEPHLI)      ,INTENT(IN) :: YPHLI
TYPE(TECLD)       ,INTENT(IN) :: YCLD
TYPE(TECLDP)      ,INTENT(IN) :: YCLDP
TYPE(TNCL  )      ,INTENT(IN) :: YNCL
!REAL(KIND=JPRB) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------
#include "fcttre.ycst.h"
#include "fcttread.ycst.h"
!     ------------------------------------------------------------------

!IF (LHOOK) CALL DR_HOOK('CLOUDSC2AD',0,ZHOOK_HANDLE)
ASSOCIATE( RCLCRIT=>YCLDP%RCLCRIT, RKCONV=>YCLDP%RKCONV, &
RLMIN=>YCLDP%RLMIN, RPECONS=>YCLDP%RPECONS,  RLPTRC=>YPHLI%RLPTRC, &
LREGCL=>YNCL%LREGCL, LEVAPLS2=>YHNC%LEVAPLS2, RETV=>YDCST%RETV, &
RG=>YDCST%RG, RCPD=>YDCST%RCPD, RLVTT=>YDCST%RLVTT, RLSTT=>YDCST%RLSTT, &
RLMLT=>YDCST%RLMLT, RTT=>YDCST%RTT, RD=>YDCST%RD, R2ES=>YDTHF%R2ES, &
R3LES=>YDTHF%R3LES, R3IES=>YDTHF%R3IES, R4LES=>YDTHF%R4LES, R4IES=>YDTHF%R4IES, & 
R5LES=>YDTHF%R5LES, R5IES=>YDTHF%R5IES, RTICE=>YDTHF%RTICE, RVTMP2=>YDTHF%RVTMP2, &
R5ALVCP=>YDTHF%R5ALVCP, R5ALSCP=>YDTHF%R5ALSCP, RALVDCP=>YDTHF%RALVDCP, &
RALSDCP=>YDTHF%RALSDCP )

!*         1.     SET-UP INPUT QUANTITIES
!                 -----------------------

!*         1.1    Set-up tunning parameters

! set up constants required

ZCKCODTL=2.0_JPRB*RKCONV*PTSPHY
ZCKCODTI=5.0_JPRB*RKCONV*PTSPHY
ZCKCODTLA=ZCKCODTL/100._JPRB
ZCKCODTIA=ZCKCODTI/100._JPRB
ZCONS2 =1.0_JPRB/(PTSPHY*RG)
ZCONS3 =RLVTT/RCPD
ZMELTP2=RTT+2.0_JPRB
ZQTMST=1.0_JPRB/PTSPHY

ZQMAX=0.5_JPRB
ZEPS1=1.E-12_JPRB
ZEPS2=1.E-10_JPRB

!     --------------------------------------------------------------------

!*         2.1    COMPUTE CRITICAL RELATIVE HUMIDITY AND RELATIVE HUMIDITY
!                 --------------------------------------------------------

! first guess values for T and q

DO JK=1,KLEV
  DO JL=KIDIA,KFDIA
    ZTP15(JL,JK) = PTM15(JL,JK) + PTSPHY*PGTENT5(JL,JK)
    ZQP15(JL,JK) = PQM15(JL,JK) + PTSPHY*PGTENQ5(JL,JK) + PSUPSAT5(JL,JK)
    ZL5  (JL,JK) = PL5  (JL,JK) + PTSPHY*PGTENL5(JL,JK)
    ZI5  (JL,JK) = PI5  (JL,JK) + PTSPHY*PGTENI5(JL,JK)
! Store trajectory arrays for adjoint
    ZTP25(JL,JK) = ZTP15(JL,JK)
    ZTP35(JL,JK) = ZTP15(JL,JK)
    ZQP25(JL,JK) = ZQP15(JL,JK)
  ENDDO
ENDDO

DO JK=1,KLEV

! Parameter for cloud formation
  ZSCALM(JK)=ZSCAL*MAX((CETA(JK)-0.2_JPRB),ZEPS1)**(0.2_JPRB)

  DO JL=KIDIA,KFDIA
! thermodynamic constants
    ZDP5(JL,JK) = PAPHP15(JL,JK+1)-PAPHP15(JL,JK)
    ZZZ5(JL,JK) =1.0_JPRB/(RCPD+RCPD*RVTMP2*ZQP15(JL,JK))
    ZLFDCP5(JL,JK) = RLMLT*ZZZ5(JL,JK)
    ZLSDCP5(JL,JK) = RLSTT*ZZZ5(JL,JK)
    ZLVDCP5(JL,JK) = RLVTT*ZZZ5(JL,JK)
    LLFLAG(JL)=.TRUE.
  ENDDO
ENDDO

!     ------------------------------------------------------------------

!*         2.2    INITIALIZATION OF CLOUD AND PRECIPITATION ARRAYS
!                 ------------------------------------------------

!       Clear cloud and freezing arrays

DO JK=1,KLEV
  DO JL=KIDIA,KFDIA
    PCLC5(JL,JK) = 0.0_JPRB
    ZRFREEZE15(JL,JK) = 0.0_JPRB
    ZRFREEZE35(JL,JK) = 0.0_JPRB
    ZEVAPR5(JL,JK) = 0.0_JPRB
    ZEVAPS5(JL,JK) = 0.0_JPRB
    PCOVPTOT5(JL,JK) = 0.0_JPRB
  ENDDO
ENDDO

!       Set to zero precipitation fluxes at the top

DO JL=KIDIA,KFDIA
  ZRFL5(JL,1) = 0.0_JPRB
  ZSFL5(JL,1) = 0.0_JPRB
  PFPLSL5(JL,1) = 0.0_JPRB
  PFPLSN5(JL,1) = 0.0_JPRB
  ZCOVPTOT5(JL,0) = 0.0_JPRB
  ZCOVPCLR5(JL,1) = 0.0_JPRB
ENDDO

! Eta value at tropopause
DO JL=KIDIA,KFDIA
  ZTRPAUS(JL)=0.1_JPRB
ENDDO
DO JK=1,KLEV-1
  DO JL=KIDIA,KFDIA
    LLO1=CETA(JK) > 0.1_JPRB .AND. CETA(JK) < 0.4_JPRB .AND. &
       & ZTP15(JL,JK) > ZTP15(JL,JK+1)
    IF(LLO1) THEN
      ZTRPAUS(JL)=CETA(JK)
    ENDIF
  ENDDO
ENDDO

!     ------------------------------------------------------------------

!*        3. COMPUTE LAYER CLOUD AMOUNTS
!            ---------------------------

! Large loop over KLEV 
! Calculates 
!   1. Diagnostic CC and prognostic cloud condensate
!   2. Convective CC and prognostic cloud condensate
!   3. Rainfall 

DO JK=KTDIA,KLEV

!       3.1   INITIALIZATION

  DO JL=KIDIA,KFDIA

    ZDR15(JL,JK) = 0.0_JPRB
    ZDR25(JL,JK) = 0.0_JPRB

!-----------------------------------
! calculate dqs/dT correction factor
!-----------------------------------

    ZOEALFAW5(JL,JK) = 0.545_JPRB &
     & * (TANH(0.17_JPRB*(ZTP25(JL,JK)-RLPTRC))+1.0_JPRB)  
    IF (ZTP25(JL,JK) < RTT) THEN
      ZFWAT5(JL,JK) = ZOEALFAW5(JL,JK)
      Z3ES(JL)=R3IES
      Z4ES(JL)=R4IES
    ELSE
      ZFWAT5(JL,JK) = 1.0_JPRB
      Z3ES(JL)=R3LES
      Z4ES(JL)=R4LES
    ENDIF
    ZFOEEW5(JL,JK) = R2ES*EXP(Z3ES(JL)*(ZTP25(JL,JK)-RTT)&
                 & / (ZTP25(JL,JK)-Z4ES(JL)))  
    ZESDP15(JL,JK) = ZFOEEW5(JL,JK)/PAPP15(JL,JK)
    ZESDP5(JL,JK)  = ZESDP15(JL,JK)
    IF (ZESDP15(JL,JK) > ZQMAX) THEN
      ZESDP5(JL,JK) = ZQMAX
    ENDIF
    
    ZFACW5(JL,JK) = R5LES/((ZTP25(JL,JK)-R4LES)**2)
    ZFACI5(JL,JK) = R5IES/((ZTP25(JL,JK)-R4IES)**2)
    ZFAC5 (JL,JK) = ZFWAT5(JL,JK)*ZFACW5(JL,JK) &
     & + (1.0_JPRB-ZFWAT5(JL,JK))*ZFACI5(JL,JK)  
    ZCOR5 (JL,JK) = 1.0_JPRB/(1.0_JPRB-RETV*ZESDP5(JL,JK))
    ZDQSDTEMP5(JL,JK) = ZFAC5(JL,JK)*ZCOR5(JL,JK)*PQS5(JL,JK)
    ZCORQS5(JL,JK) = 1.0_JPRB+ZCONS3*ZDQSDTEMP5(JL,JK)

! use clipped state

    IF (ZQP25(JL,JK) > PQS5(JL,JK)) THEN
      ZQLIM5(JL,JK) = PQS5(JL,JK)
    ELSE
      ZQLIM5(JL,JK) = ZQP25(JL,JK)
    ENDIF

! set up critical value of humidity

    ZETA3=ZTRPAUS(JL)
    ZRH1=1.0_JPRB
    ZRH2=0.35_JPRB+0.14_JPRB*((ZETA3-0.25_JPRB)/0.15_JPRB)**2&
      & +0.04_JPRB*MIN(ZETA3-0.25_JPRB,0.0_JPRB)/0.15_JPRB
    ZRH3=1.0_JPRB
    ZDETA2=0.3_JPRB
    ZDETA1=0.09_JPRB+0.16_JPRB*(0.4_JPRB-ZETA3)/0.3_JPRB
    IF (CETA(JK) < ZETA3) THEN 
      ZCRH2(JL,JK)=ZRH3
    ELSE IF (CETA(JK) >= ZETA3 .AND. CETA(JK) < (ZETA3+ZDETA2)) THEN 
      ZCRH2(JL,JK)=ZRH3+(ZRH2-ZRH3)*((CETA(JK)-ZETA3)/ZDETA2)
    ELSE IF (CETA(JK) >= (ZETA3+ZDETA2) .AND. CETA(JK) < (1.0_JPRB-ZDETA1)) THEN 
      ZCRH2(JL,JK)=ZRH2
    ELSE IF (CETA(JK) >= (1.0_JPRB-ZDETA1)) THEN 
      ZCRH2(JL,JK)=ZRH1+(ZRH2-ZRH1)*((1.0_JPRB-CETA(JK))/ZDETA1)**0.5_JPRB
    ENDIF
! Allow ice supersaturation at cold temperatures
    IF (ZTP25(JL,JK) < RTICE) THEN
      ZSUPSAT5(JL,JK)=1.8_JPRB - 3.E-03_JPRB*ZTP25(JL,JK)
    ELSE
      ZSUPSAT5(JL,JK)=1.0_JPRB
    ENDIF
    ZQSAT5(JL,JK)=PQS5(JL,JK)*ZSUPSAT5(JL,JK)
    ZQCRIT5(JL,JK)=ZCRH2(JL,JK)*ZQSAT5(JL,JK)
  ENDDO

! Simple UNIFORM distribution of total water from Letreut & Li (90)

  DO JL=KIDIA,KFDIA
    ZQT5(JL,JK)=ZQP15(JL,JK)+ZL5(JL,JK)+ZI5(JL,JK)
    IF (ZQT5(JL,JK) <= ZQCRIT5(JL,JK)) THEN
      ZCLC5(JL,JK) = 0.0_JPRB
      ZQC15(JL,JK) = 0.0_JPRB
    ELSEIF (ZQT5(JL,JK) >= ZQSAT5(JL,JK)) THEN
      ZCLC5(JL,JK) = 1.0_JPRB
      ZQC15(JL,JK) = (1.0_JPRB-ZSCALM(JK))*(ZQSAT5(JL,JK)-ZQCRIT5(JL,JK))
    ELSE
      ZQPD5(JL,JK) = ZQSAT5(JL,JK)-ZQT5(JL,JK)
      ZQCD5(JL,JK) = ZQSAT5(JL,JK)-ZQCRIT5(JL,JK)
      ZSQRT5(JL,JK) = SQRT(ZQPD5(JL,JK)/(ZQCD5(JL,JK)-ZSCALM(JK) &
       & *(ZQT5(JL,JK)-ZQCRIT5(JL,JK))))    
      ZCLC5(JL,JK) = 1.0_JPRB-ZSQRT5(JL,JK)
      ZQC15(JL,JK) = (ZSCALM(JK)*ZQPD5(JL,JK) &
       & + (1.0_JPRB-ZSCALM(JK))*ZQCD5(JL,JK)) &
       & * ZCLC5(JL,JK)**2  
    ENDIF
  ENDDO

! Add convective component

  DO JL=KIDIA,KFDIA

    ZGDP5(JL,JK) = RG/(PAPHP15(JL,JK+1)-PAPHP15(JL,JK))

    ZLUDE5(JL,JK) = PLUDE5(JL,JK)*PTSPHY*ZGDP5(JL,JK)
    IF (JK<KLEV) THEN
      LLO1=ZLUDE5(JL,JK)>=RLMIN.AND.PLU5(JL,JK+1)>=ZEPS2
    ELSE
      LLO1=.FALSE.
    ENDIF
    IF (LLO1) THEN
      PCLC5(JL,JK) = ZCLC5(JL,JK) &
       & + (1.0_JPRB-ZCLC5(JL,JK)) &
       & * (1.0_JPRB-EXP(-ZLUDE5(JL,JK)/PLU5(JL,JK+1)))  
      ZQC25(JL,JK) = ZQC15(JL,JK)+ZLUDE5(JL,JK)
    ELSE
      PCLC5(JL,JK) = ZCLC5(JL,JK)
      ZQC25(JL,JK) = ZQC15(JL,JK)
    ENDIF
  ENDDO

! Add compensating subsidence component

  DO JL=KIDIA,KFDIA
    ZFAC1(JL,JK)=1.0_JPRB/(RD*ZTP25(JL,JK))
    ZRHO5(JL,JK) = PAPP15(JL,JK)*ZFAC1(JL,JK)

    ZFAC2(JL,JK)=1.0_JPRB/(PAPP15(JL,JK)-RETV*ZFOEEW5(JL,JK))
    ZRODQSDP5(JL,JK) = -ZRHO5(JL,JK)*PQS5(JL,JK)*ZFAC2(JL,JK)

    ZLDCP5(JL,JK) = ZFWAT5(JL,JK)*ZLVDCP5(JL,JK) + (1.0_JPRB-ZFWAT5(JL,JK))*ZLSDCP5(JL,JK)

    ZFAC3(JL,JK)=1.0_JPRB/(1.0_JPRB + ZLDCP5(JL,JK)*ZDQSDTEMP5(JL,JK))
    DTDZMO5(JL,JK) = RG*(1.0_JPRB/RCPD - ZLDCP5(JL,JK)*ZRODQSDP5(JL,JK))*ZFAC3(JL,JK)

    ZDQSDZ5(JL,JK) = ZDQSDTEMP5(JL,JK)*DTDZMO5(JL,JK) - RG*ZRODQSDP5(JL,JK)

    ZFAC4(JL,JK)=1.0_JPRB/ZRHO5(JL,JK)
    LLO3(JL,JK)=(ZDQSDZ5(JL,JK)*(PMFU5(JL,JK)+PMFD5(JL,JK))*PTSPHY*ZFAC4(JL,JK) < ZQC25(JL,JK))
    IF (LLO3(JL,JK)) THEN
      ZDQC5(JL,JK) = ZDQSDZ5(JL,JK)*(PMFU5(JL,JK)+PMFD5(JL,JK))*PTSPHY*ZFAC4(JL,JK)
    ELSE
      ZDQC5(JL,JK) = ZQC25(JL,JK)
    ENDIF
    ZQC35(JL,JK) = ZQC25(JL,JK) - ZDQC5(JL,JK)
  ENDDO

! New cloud liquid/ice contents and condensation rates

  DO JL=KIDIA,KFDIA
    ZQLWC15(JL,JK)=ZQC35(JL,JK)*ZFWAT5(JL,JK)
    ZQIWC15(JL,JK)=ZQC35(JL,JK)*(1.0_JPRB-ZFWAT5(JL,JK))
    ZCONDL15(JL,JK)= (ZQLWC15(JL,JK)-ZL5(JL,JK))*ZQTMST
    ZCONDI15(JL,JK)= (ZQIWC15(JL,JK)-ZI5(JL,JK))*ZQTMST
  ENDDO

! Calculate precipitation overlap. 
! Simple formulation based on maximum overlap.

  DO JL=KIDIA,KFDIA
    IF (PCLC5(JL,JK) > ZCOVPTOT5(JL,JK-1)) THEN ! total rain frac
      ZCOVPTOT15(JL,JK) = PCLC5(JL,JK)
    ELSE
      ZCOVPTOT15(JL,JK) = ZCOVPTOT5(JL,JK-1)
    ENDIF
    ZCOVPTOT5(JL,JK) = ZCOVPTOT15(JL,JK)

    ZCOVPCLR15(JL,JK) = ZCOVPTOT5(JL,JK)-PCLC5(JL,JK)
    ZCOVPCLR5(JL,JK) = ZCOVPCLR15(JL,JK)
    IF (ZCOVPCLR15(JL,JK) < 0.0_JPRB) THEN
      ZCOVPCLR5(JL,JK) = 0.0_JPRB
    ENDIF
  ENDDO

!*         3.3    CALCULATE PRECIPITATION

!    Melting of incoming snow

  DO JL=KIDIA,KFDIA
    IF (ZSFL5(JL,JK) /= 0.0_JPRB) THEN
      ZCONS5(JL,JK) = ZCONS2*ZDP5(JL,JK)/ZLFDCP5(JL,JK)
      IF ((ZTP25(JL,JK)-ZMELTP2) > 0.0_JPRB) THEN
        ZZ2S5(JL,JK) = ZCONS5(JL,JK)*(ZTP25(JL,JK)-ZMELTP2)
      ELSE
        ZZ2S5(JL,JK) = 0.0_JPRB
      ENDIF
      IF (ZSFL5(JL,JK) <= ZZ2S5(JL,JK)) THEN
        ZSNMLT5(JL,JK) = ZSFL5(JL,JK)
      ELSE
        ZSNMLT5(JL,JK) = ZZ2S5(JL,JK)
      ENDIF
      ZRFLN5(JL) = ZRFL5(JL,JK)+ZSNMLT5(JL,JK)
      ZSFLN5(JL) = ZSFL5(JL,JK)-ZSNMLT5(JL,JK)
      ZTP15(JL,JK) = ZTP25(JL,JK)-ZSNMLT5(JL,JK)/ZCONS5(JL,JK)
    ELSE
      ZRFLN5(JL) = ZRFL5(JL,JK)
      ZSFLN5(JL) = ZSFL5(JL,JK)
    ENDIF
  ENDDO

!    Diagnostic calculation of rain production from cloud water

  DO JL=KIDIA,KFDIA

!    Diagnostic calculation of rain production from cloud liquid water

    IF (PCLC5(JL,JK) > ZEPS2) THEN
      IF (LEVAPLS2 .OR. LDRAIN1D) THEN
        ZLCRIT = 1.9_JPRB*RCLCRIT
      ELSE
        ZLCRIT = RCLCRIT*2._JPRB
      ENDIF
      ZCLDL5(JL,JK) = ZQLWC15(JL,JK)/PCLC5(JL,JK)               ! in-cloud liquid 
      ZEXP35(JL,JK) = EXP(-(ZCLDL5(JL,JK)/ZLCRIT)**2)
      ZDL5(JL,JK) = ZCKCODTL*(1.0_JPRB-ZEXP35(JL,JK))
      ZEXPDL5(JL,JK) = EXP(-ZDL5(JL,JK))
      ZLNEW5 = PCLC5(JL,JK)*ZCLDL5(JL,JK)*ZEXPDL5(JL,JK)
      ZPRR5(JL,JK) = ZQLWC15(JL,JK)-ZLNEW5
      ZQLWC5(JL,JK) = ZQLWC15(JL,JK)-ZPRR5(JL,JK)
    ELSE
      ZPRR5(JL,JK) = 0.0_JPRB
      ZQLWC5(JL,JK) = ZQLWC15(JL,JK)
    ENDIF

!    Diagnostic calculation of rain production from cloud ice

    IF (PCLC5(JL,JK) > ZEPS2) THEN
      IF (LEVAPLS2 .OR. LDRAIN1D) THEN
        ZLCRIT = 1.E-04_JPRB
      ELSE
        ZLCRIT = RCLCRIT*2._JPRB
      ENDIF
      ZCLDI5(JL,JK) = ZQIWC15(JL,JK)/PCLC5(JL,JK)                ! in-cloud liquid 
      ZEXP15(JL,JK) = EXP(0.025_JPRB*(ZTP15(JL,JK)-RTT))
      ZEXP25(JL,JK) = EXP(-(ZCLDI5(JL,JK)/ZLCRIT)**2)
      ZDI5(JL,JK) = ZCKCODTI * ZEXP15(JL,JK) * (1.0_JPRB-ZEXP25(JL,JK))
      ZEXPDI5(JL,JK) = EXP(-ZDI5(JL,JK))
      ZINEW5 = PCLC5(JL,JK)*ZCLDI5(JL,JK)*ZEXPDI5(JL,JK)
      ZPRS5(JL,JK) = ZQIWC15(JL,JK)-ZINEW5
      ZQIWC5(JL,JK) = ZQIWC15(JL,JK)-ZPRS5(JL,JK)
    ELSE
      ZPRS5(JL,JK) = 0.0_JPRB
      ZQIWC5(JL,JK) = ZQIWC15(JL,JK)
    ENDIF

!    New precipitation

    ZDR15(JL,JK) = ZCONS2*ZDP5(JL,JK)*(ZPRR5(JL,JK)+ZPRS5(JL,JK))

! Rain fraction (different from cloud liquid water fraction!)
    IF (ZTP15(JL,JK) < RTT) THEN
      ZRFREEZE15(JL,JK)=ZCONS2*ZDP5(JL,JK)*ZPRR5(JL,JK)
      ZFWATR15(JL,JK)=0.0_JPRB
    ELSE
      ZFWATR15(JL,JK)=1.0_JPRB
    ENDIF 

    ZRN5 = ZFWATR15(JL,JK)*ZDR15(JL,JK)
    ZSN5 = (1.0_JPRB-ZFWATR15(JL,JK))*ZDR15(JL,JK)
    ZRFLN5(JL) = ZRFLN5(JL) + ZRN5
    ZSFLN5(JL) = ZSFLN5(JL) + ZSN5
! Store trajectory for adjoint
    ZRFLN25(JL,JK) = ZRFLN5(JL)
    ZSFLN25(JL,JK) = ZSFLN5(JL)

!   Precip evaporation

    ZPRTOT5(JL,JK) = ZRFLN5(JL)+ZSFLN5(JL)
    LLO2=ZPRTOT5(JL,JK)>ZEPS2 .AND. ZCOVPCLR5(JL,JK)>ZEPS2 &
     & .AND. (LEVAPLS2 .OR. LDRAIN1D)

    IF (LLO2) THEN
      ZPRECLR15(JL,JK) = ZPRTOT5(JL,JK)*ZCOVPCLR5(JL,JK) &
       & / ZCOVPTOT15(JL,JK)  

!     This is the humidity in the moistest zcovpclr region

      ZQE5(JL,JK) = PQS5(JL,JK)-(PQS5(JL,JK)-ZQLIM5(JL,JK)) &
       & * ZCOVPCLR5(JL,JK) / (1.0_JPRB-PCLC5(JL,JK))**2  
      ZBETA5(JL,JK) = RG*RPECONS*(SQRT(PAPP15(JL,JK) &
       & / PAPHP15(JL,KLEV+1))/5.09E-3_JPRB*ZPRECLR15(JL,JK) &
       & / ZCOVPCLR5(JL,JK))**0.5777_JPRB  

!     implicit solution:

      ZB5(JL,JK) = PTSPHY*ZBETA5(JL,JK)*(PQS5(JL,JK)-ZQE5(JL,JK)) &
       & / (1.0_JPRB+ZBETA5(JL,JK)*PTSPHY*ZCORQS5(JL,JK))  

!     exact solution:

!     ZEXP5(JL,JK) = EXP(-ZBETA5(JL,JK)*ZCORQS5(JL,JK)*PTSPHY)
!     ZB5(JL,JK) = (PQS5(JL,JK)-ZQE5(JL,JK))*(_ONE_-ZEXP5(JL,JK)) &
!      &         / ZCORQS5(JL,JK)

      ZDTGDP5(JL,JK) =PTSPHY*RG/(PAPHP15(JL,JK+1)-PAPHP15(JL,JK))

      ZDPR15(JL,JK) = ZCOVPCLR5(JL,JK)*ZB5(JL,JK)/ZDTGDP5(JL,JK)
      ZDPR5 (JL,JK) = ZDPR15(JL,JK)
      IF (ZDPR15(JL,JK) > ZPRECLR15(JL,JK)) THEN
        ZDPR5(JL,JK) = ZPRECLR15(JL,JK)
      ENDIF

! take away from clr sky flux
      ZPRECLR5(JL,JK) = ZPRECLR15(JL,JK)-ZDPR5 (JL,JK)
      IF (ZPRECLR5(JL,JK) <= 0.0_JPRB) THEN !reset
        ZCOVPTOT5(JL,JK) = PCLC5(JL,JK)
      ENDIF
      PCOVPTOT5(JL,JK) = ZCOVPTOT5(JL,JK)

! warm proportion
      ZEVAPR5(JL,JK) = ZDPR5(JL,JK)*ZRFLN25(JL,JK)/ZPRTOT5(JL,JK)    
      ZRFLN5(JL) = ZRFLN5(JL)-ZEVAPR5(JL,JK) 
     
! ice proportion
      ZEVAPS5(JL,JK) = ZDPR5(JL,JK)*ZSFLN25(JL,JK)/ZPRTOT5(JL,JK)        
      ZSFLN5(JL) = ZSFLN5(JL)-ZEVAPS5(JL,JK)
    ENDIF

  ENDDO

!   Incrementation of T and Q and fluxes' swap

  DO JL=KIDIA,KFDIA
    ZDQDT5=-(ZCONDL15(JL,JK)+ZCONDI15(JL,JK)) &
         & +(PLUDE5(JL,JK)+ZEVAPR5(JL,JK)+ZEVAPS5(JL,JK))*ZGDP5(JL,JK)

    ZDTDT5= ZLVDCP5(JL,JK)*ZCONDL15(JL,JK)+ZLSDCP5(JL,JK)*ZCONDI15(JL,JK) &
        & -( ZLVDCP5(JL,JK)*ZEVAPR5(JL,JK)+ZLSDCP5(JL,JK)*ZEVAPS5(JL,JK) &
        & +PLUDE5(JL,JK)*(ZFWAT5(JL,JK)*ZLVDCP5(JL,JK)+ &
        & (1.0_JPRB-ZFWAT5(JL,JK))*ZLSDCP5(JL,JK))&
        & -(ZLSDCP5(JL,JK)-ZLVDCP5(JL,JK))*ZRFREEZE15(JL,JK) )&
        & *ZGDP5(JL,JK)

! first guess T and Q
    ZTP35(JL,JK) = ZTP15(JL,JK) + PTSPHY*ZDTDT5
    ZQP15(JL,JK) = ZQP25(JL,JK) + PTSPHY*ZDQDT5
    ZTPB5(JL,JK) = ZTP35(JL,JK)
    ZQPB5(JL,JK) = ZQP15(JL,JK)
    
    ZPP5(JL) = PAPP15(JL,JK)
    ZQOLD5(JL,JK) = ZQP15(JL,JK)
  ENDDO

! clipping of final qv

! CALL CUADJTQS  ( KIDIA, KFDIA, KLON, KLEV, IK,&
!  & ZPP5 , ZTP35 , ZQP15, LLFLAG, ICALL,  YDCST, YDTHF  )  


 ZQMAX=0.5_JPRB
 
 !     2.           CALCULATE CONDENSATION AND ADJUST T AND Q ACCORDINGLY
 !                  -----------------------------------------------------
 
 !*    ICE-WATER THERMODYNAMICAL FUNCTIONS
 
 DO JL=KIDIA,KFDIA
   IF (ZTP35(JL,JK) > RTT) THEN
     Z3ES(JL)=R3LES
     Z4ES(JL)=R4LES
     Z5ALCP(JL)=R5ALVCP
     ZALDCP(JL)=RALVDCP
   ELSE
     Z3ES(JL)=R3IES
     Z4ES(JL)=R4IES
     Z5ALCP(JL)=R5ALSCP
     ZALDCP(JL)=RALSDCP
   ENDIF
 ENDDO
 
 
   DO JL=KIDIA,KFDIA
     ZQP    =1.0_JPRB/ZPP5(JL)
     ZTARG(JL)    =ZTP35(JL,JK)
     ZFOEEW(JL)    =R2ES*EXP(Z3ES(JL)*(ZTARG(JL)    -RTT)/(ZTARG(JL)    -Z4ES(JL)))
     ZQSAT    =ZQP(JL)    *ZFOEEW(JL)    
     IF (ZQSAT(JL)     > ZQMAX) THEN
       ZQSAT(JL)    =ZQMAX
     ENDIF
     ZCOR(JL)    =1.0_JPRB/(1.0_JPRB-RETV  *ZQSAT(JL)    )
     ZQSAT(JL)    =ZQSAT(JL)    *ZCOR(JL)    
     Z2S(JL)    =Z5ALCP(JL)/(ZTARG(JL)    -Z4ES(JL))**2
     ZCOND1(JL)    =(ZQP15(JL,JK)-ZQSAT(JL)    )/(1.0_JPRB+ZQSAT(JL)    *ZCOR(JL)    *Z2S(JL)    )
     ZTP35(JL,JK)=ZTP35(JL,JK)+ZALDCP(JL)*ZCOND1(JL)    
     ZQP15(JL,JK)=ZQP15(JL,JK)-ZCOND1(JL)    
     ZTARG(JL)    =ZTP35(JL,JK)
     ZFOEEW(JL)    =R2ES*EXP(Z3ES(JL)*(ZTARG(JL)    -RTT)/(ZTARG(JL)    -Z4ES(JL)))
     ZQSAT(JL)    =ZQP(JL)    *ZFOEEW(JL)    
     IF (ZQSAT(JL)     > ZQMAX) THEN
       ZQSAT(JL)    =ZQMAX
     ENDIF
     ZCOR(JL)    =1.0_JPRB/(1.0_JPRB-RETV  *ZQSAT(JL)    )
     ZQSAT(JL)    =ZQSAT(JL)    *ZCOR(JL)    
     Z2S (JL)   =Z5ALCP(JL)/(ZTARG(JL)    -Z4ES(JL))**2
     ZCOND1(JL)    =(ZQP15(JL,JK)-ZQSAT(JL)    )/(1.0_JPRB+ZQSAT(JL)    *ZCOR(JL)    *Z2S(JL)    )
     ZTP35(JL,JK)=ZTP35(JL,JK)+ZALDCP(JL)*ZCOND1(JL)    
     ZQP15(JL,JK)=ZQP15(JL,JK)-ZCOND1(JL)    
   ENDDO
 !!cznak
  
  DO JL=KIDIA,KFDIA
    IF ((ZQOLD5(JL,JK)-ZQP15(JL,JK)) >= 0.0_JPRB) THEN
      ZDQ5(JL,JK) = ZQOLD5(JL,JK)-ZQP15(JL,JK)
    ELSE
      ZDQ5(JL,JK) = 0.0_JPRB
    ENDIF
    ZDR25(JL,JK) = ZCONS2*ZDP5(JL,JK)*ZDQ5(JL,JK)    

    IF (ZTP35(JL,JK) < RTT) THEN
      ZRFREEZE25=ZFWAT5(JL,JK)*ZDR25(JL,JK)
      ZFWATR25(JL,JK)=0.0_JPRB
    ELSE
      ZRFREEZE25=0.0_JPRB
      ZFWATR25(JL,JK)=1.0_JPRB
    ENDIF 

    ZRN5 = ZFWATR25(JL,JK)*ZDR25(JL,JK)
    ZSN5 = (1.0_JPRB-ZFWATR25(JL,JK))*ZDR25(JL,JK) 

! Note: The extra condensation due to the adjustment goes directly to precipitation
    ZCONDL25(JL,JK)=ZCONDL15(JL,JK)+ ZFWATR25(JL,JK)*ZDQ5(JL,JK)*ZQTMST
    ZCONDI25(JL,JK)=ZCONDI15(JL,JK)+ (1.0_JPRB-ZFWATR25(JL,JK))*ZDQ5(JL,JK)*ZQTMST

    ZRFLN5(JL) = ZRFLN5(JL) + ZRN5
    ZSFLN5(JL) = ZSFLN5(JL) + ZSN5
    ZRFREEZE35(JL,JK)=ZRFREEZE15(JL,JK)+ZRFREEZE25
  ENDDO
    
  DO JL=KIDIA,KFDIA
    ZDQDT5=-(ZCONDL25(JL,JK)+ZCONDI25(JL,JK)) &
            & +(PLUDE5(JL,JK)+ZEVAPR5(JL,JK)+ZEVAPS5(JL,JK))*ZGDP5(JL,JK)

    ZDTDT5= ZLVDCP5(JL,JK)*ZCONDL25(JL,JK)+ZLSDCP5(JL,JK)*ZCONDI25(JL,JK) &
            & -( ZLVDCP5(JL,JK)*ZEVAPR5(JL,JK)+ZLSDCP5(JL,JK)*ZEVAPS5(JL,JK) &
            & +PLUDE5(JL,JK)*(ZFWAT5(JL,JK)*ZLVDCP5(JL,JK)+ &
            & (1.0_JPRB-ZFWAT5(JL,JK))*ZLSDCP5(JL,JK))&
            & -(ZLSDCP5(JL,JK)-ZLVDCP5(JL,JK))*ZRFREEZE35(JL,JK) )&
            & *ZGDP5(JL,JK)

    ZDLDT5=(ZQLWC5(JL,JK)-ZL5(JL,JK))*ZQTMST

    ZDIDT5=(ZQIWC5(JL,JK)-ZI5(JL,JK))*ZQTMST

    PTENQ5(JL,JK) = ZDQDT5
    PTENT5(JL,JK) = ZDTDT5
    PTENL5(JL,JK) = ZDLDT5
    PTENI5(JL,JK) = ZDIDT5

    PFPLSL5(JL,JK+1) = ZRFLN5(JL)
    PFPLSN5(JL,JK+1) = ZSFLN5(JL)
  ENDDO

  DO JL=KIDIA,KFDIA
    ZRFL5(JL,JK+1) = ZRFLN5(JL)
    ZSFL5(JL,JK+1) = ZSFLN5(JL)
  ENDDO

ENDDO  !jk

!*     ENTHALPY FLUXES DUE TO PRECIPITATION
!      ------------------------------------

DO JK=1,KLEV+1
  DO JL=KIDIA,KFDIA
    PFHPSL5(JL,JK) = -PFPLSL5(JL,JK)*RLVTT
    PFHPSN5(JL,JK) = -PFPLSN5(JL,JK)*RLSTT
  ENDDO
ENDDO

!     ------------------------------------------------------------------

!                 ----- ADJOINT COMPUTATION ------

!     ------------------------------------------------------------------

!*                        INITIALIZATIONS
!                         ---------------

ZRFL(:)     = 0.0_JPRB
ZSFL(:)     = 0.0_JPRB
ZDQ(:)      = 0.0_JPRB
ZQOLD(:)    = 0.0_JPRB
ZPP(:)      = 0.0_JPRB
ZQCRIT(:)   = 0.0_JPRB
ZGDP(:)     = 0.0_JPRB
ZRFLN(:)    = 0.0_JPRB
ZSFLN(:)    = 0.0_JPRB
ZDTGDP(:)   = 0.0_JPRB
ZCOVPCLR(:) = 0.0_JPRB
ZDQSDTEMP(:) = 0.0_JPRB
ZCOVPTOT(:) = 0.0_JPRB
ZCORQS(:)   = 0.0_JPRB
ZQLIM(:)    = 0.0_JPRB
ZFWAT(:)    = 0.0_JPRB

ZDP(:,:)    = 0.0_JPRB
ZLFDCP(:,:) = 0.0_JPRB
ZLSDCP(:,:) = 0.0_JPRB
ZLVDCP(:,:) = 0.0_JPRB
ZTP1(:,:)   = 0.0_JPRB
ZQP1(:,:)   = 0.0_JPRB
ZL(:,:)     = 0.0_JPRB
ZI(:,:)     = 0.0_JPRB
ZQLWC(:,:)  = 0.0_JPRB
ZQIWC(:,:)  = 0.0_JPRB
ZLUDE(:,:)  = 0.0_JPRB
ZEVAPR(:,:) = 0.0_JPRB
ZEVAPS(:,:) = 0.0_JPRB
ZCONDL(:,:) = 0.0_JPRB
ZCONDI(:,:) = 0.0_JPRB
ZRFREEZE(:,:) = 0.0_JPRB

!*     ENTHALPY FLUXES DUE TO PRECIPITATION
!      ------------------------------------

DO JK=KLEV+1,1,-1
  DO JL=KIDIA,KFDIA
    PFPLSN(JL,JK)=PFPLSN(JL,JK)-PFHPSN(JL,JK)*RLSTT
    PFHPSN(JL,JK)=0.0_JPRB
    PFPLSL(JL,JK)=PFPLSL(JL,JK)-PFHPSL(JL,JK)*RLVTT
    PFHPSL(JL,JK)=0.0_JPRB
  ENDDO
ENDDO

!     ------------------------------------------------------------------

!*        3. COMPUTE LAYER CLOUD AMOUNTS
!            ---------------------------

! Large loop over KLEV 
! Calculates 
!   1. diagnostic CC and QL
!   2. Convective CC and QL
!   3. Rainfall 

DO JK=KLEV,KTDIA,-1

!*         3.3    CALCULATE PRECIPITATION

!   Incrementation of T and Q and fluxes' swap

  DO JL=KIDIA,KFDIA
    ZSFLN(JL) = ZSFLN(JL)+ZSFL(JL)
    ZSFL (JL) = 0.0_JPRB
    ZRFLN(JL) = ZRFLN(JL)+ZRFL(JL)
    ZRFL (JL) = 0.0_JPRB
  ENDDO

  DO JL=KIDIA,KFDIA

    ZDTDT = 0.0_JPRB 
    ZDQDT = 0.0_JPRB 
    ZDLDT = 0.0_JPRB 
    ZDIDT = 0.0_JPRB 
   
    ZSFLN(JL) = ZSFLN(JL)+PFPLSN(JL,JK+1)
    PFPLSN(JL,JK+1) = 0.0_JPRB
    ZRFLN(JL) = ZRFLN(JL)+PFPLSL(JL,JK+1)
    PFPLSL(JL,JK+1) = 0.0_JPRB
    
    ZDTDT = ZDTDT + PTENT (JL,JK)
    ZDQDT = ZDQDT + PTENQ (JL,JK)
    ZDLDT = ZDLDT + PTENL (JL,JK)
    ZDIDT = ZDIDT + PTENI (JL,JK)
    PTENT (JL,JK) = 0.0_JPRB
    PTENQ (JL,JK) = 0.0_JPRB
    PTENL (JL,JK) = 0.0_JPRB
    PTENI (JL,JK) = 0.0_JPRB

! qice tendency
    ZI(JL,JK)    = ZI(JL,JK)    - ZQTMST*ZDIDT
    ZQIWC(JL,JK) = ZQIWC(JL,JK) + ZQTMST*ZDIDT
    ZDIDT = 0.0_JPRB

! qliq tendency
    ZL(JL,JK)    = ZL(JL,JK)    - ZQTMST*ZDLDT
    ZQLWC(JL,JK) = ZQLWC(JL,JK) + ZQTMST*ZDLDT
    ZDLDT = 0.0_JPRB

! T tendency
    ZGDP (JL) = ZGDP (JL) - ZDTDT  & 
            & * (ZLVDCP5(JL,JK)*ZEVAPR5(JL,JK)+ZLSDCP5(JL,JK)*ZEVAPS5(JL,JK) &
            & +  PLUDE5(JL,JK)*(ZFWAT5(JL,JK)*ZLVDCP5(JL,JK) &
            & + (1.0_JPRB-ZFWAT5(JL,JK))*ZLSDCP5(JL,JK))&
            & - (ZLSDCP5(JL,JK)-ZLVDCP5(JL,JK))*ZRFREEZE35(JL,JK))
    ZCONDL(JL,JK) = ZCONDL(JL,JK) + ZDTDT * ZLVDCP5(JL,JK)
    ZCONDI(JL,JK) = ZCONDI(JL,JK) + ZDTDT * ZLSDCP5(JL,JK)
    ZEVAPR(JL,JK) = ZEVAPR(JL,JK) - ZDTDT * ZLVDCP5(JL,JK)*ZGDP5(JL,JK)
    ZEVAPS(JL,JK) = ZEVAPS(JL,JK) - ZDTDT * ZLSDCP5(JL,JK)*ZGDP5(JL,JK)
    ZLVDCP(JL,JK) = ZLVDCP(JL,JK) + ZDTDT *(ZCONDL25(JL,JK)-ZEVAPR5(JL,JK)*ZGDP5(JL,JK))
    ZLSDCP(JL,JK) = ZLSDCP(JL,JK) + ZDTDT *(ZCONDI25(JL,JK)-ZEVAPS5(JL,JK)*ZGDP5(JL,JK))
    PLUDE(JL,JK)  = PLUDE(JL,JK)  - ZDTDT * ZGDP5(JL,JK) &
                & * (ZFWAT5(JL,JK)*ZLVDCP5(JL,JK) &
                & + (1.0_JPRB-ZFWAT5(JL,JK))*ZLSDCP5(JL,JK))
    ZLVDCP(JL,JK) = ZLVDCP(JL,JK) - ZDTDT * PLUDE5(JL,JK)*ZGDP5(JL,JK) &
                & * ZFWAT5(JL,JK) 
    ZLSDCP(JL,JK) = ZLSDCP(JL,JK) - ZDTDT * PLUDE5(JL,JK)*ZGDP5(JL,JK) &
                & * (1.0_JPRB-ZFWAT5(JL,JK))
    ZFWAT(JL) = ZFWAT(JL) - ZDTDT * PLUDE5(JL,JK)*ZGDP5(JL,JK) &
            & * (ZLVDCP5(JL,JK)-ZLSDCP5(JL,JK)) 
    ZLSDCP(JL,JK) = ZLSDCP(JL,JK) + ZDTDT * ZRFREEZE35(JL,JK)*ZGDP5(JL,JK)
    ZLVDCP(JL,JK) = ZLVDCP(JL,JK) - ZDTDT * ZRFREEZE35(JL,JK)*ZGDP5(JL,JK)
    ZRFREEZE (JL,JK) = ZRFREEZE (JL,JK) + ZDTDT *(ZLSDCP5(JL,JK)-ZLVDCP5(JL,JK)) &
                   & * ZGDP5(JL,JK)
    ZDTDT=0.0_JPRB

! q tendency
    ZGDP(JL) = ZGDP(JL) + ZDQDT *(PLUDE5(JL,JK)+ZEVAPR5(JL,JK)+ZEVAPS5(JL,JK))
    PLUDE(JL,JK)  = PLUDE(JL,JK)  + ZDQDT * ZGDP5(JL,JK)
    ZEVAPR(JL,JK) = ZEVAPR(JL,JK) + ZDQDT * ZGDP5(JL,JK)
    ZEVAPS(JL,JK) = ZEVAPS(JL,JK) + ZDQDT * ZGDP5(JL,JK)
    ZCONDL(JL,JK) = ZCONDL(JL,JK) - ZDQDT 
    ZCONDI(JL,JK) = ZCONDI(JL,JK) - ZDQDT 
    ZDQDT=0.0_JPRB
  ENDDO

! clipping of final qv

  DO JL=KIDIA,KFDIA
    ZFWATR = 0.0_JPRB
    ZSN = 0.0_JPRB
    ZRN = 0.0_JPRB
    ZDR2 = 0.0_JPRB

    ZRFREEZE2 = ZRFREEZE (JL,JK)

    ZSN = ZSN + ZSFLN (JL)
    ZRN = ZRN + ZRFLN (JL)

! Note: The extra condensation due to the adjustment goes directly to precipitation
    ZDQ (JL) = ZDQ (JL) + ZCONDI(JL,JK) * (1.0_JPRB-ZFWATR25(JL,JK))*ZQTMST
    ZFWATR   = ZFWATR   - ZCONDI(JL,JK) * ZDQ5(JL,JK)*ZQTMST 
    ZDQ (JL) = ZDQ (JL) + ZCONDL(JL,JK) * ZFWATR25(JL,JK)*ZQTMST
    ZFWATR   = ZFWATR   + ZCONDL(JL,JK) * ZDQ5(JL,JK)*ZQTMST 

    ZDR2   = ZDR2   + (1.0_JPRB-ZFWATR25(JL,JK))*ZSN
    ZFWATR = ZFWATR - ZDR25(JL,JK)*ZSN
    
    ZDR2   = ZDR2   + ZFWATR25(JL,JK)*ZRN
    ZFWATR = ZFWATR + ZDR25(JL,JK)*ZRN

! Update rain fraction and freezing.
! Note: impact of new temperature ZTP1 on ZFWAT is neglected here.
    IF (ZTP35(JL,JK) < RTT) THEN
      ZFWATR=0.0_JPRB

      ZFWAT (JL) = ZFWAT (JL)+ ZDR25(JL,JK)*ZRFREEZE2
      ZDR2       = ZDR2      + ZFWAT5(JL,JK)*ZRFREEZE2
    ELSE
      ZFWATR=0.0_JPRB
    ENDIF 

    ZDQ(JL) = ZDQ(JL)+ZCONS2*ZDP5(JL,JK)*ZDR2 
    ZDP(JL,JK) = ZDP(JL,JK)+ZCONS2*ZDQ5(JL,JK)*ZDR2 
    ZDR2 = 0.0_JPRB

    IF ((ZQOLD5(JL,JK)-ZQP15(JL,JK)) >= 0.0_JPRB) THEN
! Regularization
      IF (LREGCL) THEN
        ZDQ (JL) = ZDQ (JL) * 0.7_JPRB
      ENDIF
      ZQOLD (JL) = ZQOLD (JL)+ZDQ (JL)
      ZQP1 (JL,JK) = ZQP1 (JL,JK)-ZDQ (JL)
    ENDIF
    ZDQ (JL) = 0.0_JPRB

    ZPP5(JL) = PAPP15(JL,JK)
  ENDDO
    
! IK=JK
!CALL CUADJTQSAD ( KIDIA, KFDIA, KLON, KLEV, IK,&
! & ZPP5 , ZTPB5 , ZQPB5,&
! & ZPP  , ZTP1  , ZQP1 , LLFLAG, ICALL, YDCST, YDTHF )  
!----- begin of cuadjtqsad inlining

ZQMAX=0.5_JPRB

!----------------------------------------------------------------------

!*              ------  TRAJECTORY COMPUTATIONS  ------

!----------------------------------------------------------------------

!     2.           CALCULATE CONDENSATION AND ADJUST T AND Q ACCORDINGLY
!                  -----------------------------------------------------

!*    ICE-WATER THERMODYNAMICAL FUNCTIONS

DO JL=KIDIA,KFDIA
  IF (ZTPB5(JL,JK) > RTT) THEN
    Z3ES(JL)=R3LES
    Z4ES(JL)=R4LES
    Z5ALCP(JL)=R5ALVCP
    ZALDCP(JL)=RALVDCP
  ELSE
    Z3ES(JL)=R3IES
    Z4ES(JL)=R4IES
    Z5ALCP(JL)=R5ALSCP
    ZALDCP(JL)=RALSDCP
  ENDIF
ENDDO

  DO JL=KIDIA,KFDIA
    ZQP5(JL)=1.0_JPRB/ZPP5(JL)
    ZTARG5(JL)=ZTPB5(JL,JK)
    ZFOEEW5T(JL,JK)=R2ES*EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/(ZTARG5(JL)-Z4ES(JL)))
    ZFOEEW55B(JL)=ZFOEEW5T(JL,JK)
    ZQSAT5T(JL,JK)=ZQP5(JL)*ZFOEEW5T(JL,JK)
    LLTEST2(JL)=ZQSAT5T(JL,JK) > ZQMAX
    IF (ZQSAT5T(JL,JK) > ZQMAX) THEN
      ZQSAT5T(JL,JK)=ZQMAX
    ENDIF
    ZCOR5T(JL,JK)=1.0_JPRB/(1.0_JPRB-RETV  *ZQSAT5T(JL,JK))
    ZQSAT55D(JL)=ZQSAT5T(JL,JK)
    ZQSAT5T(JL,JK)=ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)
    ZTARG55B(JL)=ZTARG5(JL)
    Z2S5(JL)=    Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**2
    ZQSAT55B(JL)=ZQSAT5T(JL,JK)
    ZCOR55B(JL)=ZCOR5T(JL,JK)
    Z2S55B(JL)=Z2S5(JL)
    ZQ55B(JL)=ZQPB5(JL,JK)
    ZCOND15(JL)=(ZQPB5(JL,JK)-ZQSAT5T(JL,JK))/(1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))
    ZTPB5(JL,JK)=ZTPB5(JL,JK)+ZALDCP(JL)*ZCOND15(JL)
    ZQPB5(JL,JK)=ZQPB5(JL,JK)-ZCOND15(JL)
  ENDDO

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZTARG5(JL)=ZTPB5(JL,JK)
    ZFOEEW5T(JL,JK)=R2ES*EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/(ZTARG5(JL)-Z4ES(JL)))
    ZFOEEW55A(JL)=ZFOEEW5T(JL,JK)
    ZQSAT5T(JL,JK)=ZQP5(JL)*ZFOEEW5T(JL,JK)
    LLTEST1(JL)=ZQSAT5T(JL,JK) > ZQMAX
    IF (ZQSAT5T(JL,JK) > ZQMAX) THEN
      ZQSAT5T(JL,JK)=ZQMAX
    ENDIF
    ZCOR5T(JL,JK)=1.0_JPRB/(1.0_JPRB-RETV  *ZQSAT5T(JL,JK))
    ZQSAT55C(JL)=ZQSAT5T(JL,JK)
    ZQSAT5T(JL,JK)=ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)
    ZTARG55A(JL)=ZTARG5(JL)
    Z2S5(JL)=    Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**2
    ZQSAT55A(JL)=ZQSAT5T(JL,JK)
    ZCOR55A(JL)=ZCOR5T(JL,JK)
    Z2S55A(JL)=Z2S5(JL)
    ZQ55A(JL)=ZQPB5(JL,JK)
    ZCOND15(JL)=(ZQPB5(JL,JK)-ZQSAT5T(JL,JK))/(1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))
    ZTPB5(JL,JK)=ZTPB5(JL,JK)+ZALDCP(JL)*ZCOND15(JL)
    ZQPB5(JL,JK)=ZQPB5(JL,JK)-ZCOND15(JL)
  ENDDO


!----------------------------------------------------------------------

!*                 ------ ADJOINT COMPUTATIONS ------

!----------------------------------------------------------------------

!*                 INITIALISATION OF LOCAL ARRAYS

ZTARG(:) =0.0_JPRB
ZFOEEW(:)=0.0_JPRB
ZQSAT(:) =0.0_JPRB
ZCOR(:)  =0.0_JPRB
Z2S(:)   =0.0_JPRB
ZCOND1(:)=0.0_JPRB
ZCOND(:) =0.0_JPRB
ZQP(:)   =0.0_JPRB


!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZCOND1 (JL) = ZCOND1 (JL) - ZQP1 (JL,JK)
    ZCOND1 (JL) = ZCOND1 (JL) + ZALDCP(JL)*ZTP1 (JL,JK)
    ZQSAT5T(JL,JK)=ZQSAT55A(JL)
    ZCOR5T(JL,JK)=ZCOR55A(JL)
    Z2S5(JL)=Z2S55A(JL)
    ZQP1 (JL,JK) = ZQP1 (JL,JK) + ZCOND1 (JL)/&
     & (1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)/&
     & (1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)*&
     & (ZQ55A(JL)-ZQSAT5T(JL,JK))*ZCOR5T(JL,JK)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))**2  
    ZCOR (JL) = ZCOR (JL) - ZCOND1 (JL)*&
     & (ZQ55A(JL)-ZQSAT5T(JL,JK))*ZQSAT5T(JL,JK)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))**2  
    Z2S (JL) = Z2S (JL) - ZCOND1 (JL)*&
     & (ZQ55A(JL)-ZQSAT5T(JL,JK))*ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)/&
     & (1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))**2  
    ZCOND1 (JL) = 0.0_JPRB
    ZTARG5(JL)=ZTARG55A(JL)
    ZTARG(JL) = ZTARG(JL) - 2.0_JPRB*Z2S (JL)*&
     & Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**3  
    Z2S (JL) = 0.0_JPRB
    ZQSAT5T(JL,JK)=ZQSAT55C(JL)
    ZCOR (JL) = ZCOR (JL) + ZQSAT (JL)*ZQSAT5T(JL,JK)
    ZQSAT (JL) = ZQSAT (JL)*ZCOR5T(JL,JK)
    ZQSAT(JL) = ZQSAT(JL) + ZCOR(JL)*RETV/(1.0_JPRB-RETV*ZQSAT5T(JL,JK))**2
    ZCOR(JL) = 0.0_JPRB
    IF (LLTEST1(JL)) THEN
      ZQSAT (JL)=0.0_JPRB
    ENDIF
    ZFOEEW (JL) = ZFOEEW (JL) + ZQSAT (JL)*ZQP5(JL)
    ZFOEEW5T(JL,JK)=ZFOEEW55A(JL)
    ZQP (JL) = ZQP (JL) + ZQSAT (JL)*ZFOEEW5T(JL,JK)
    ZQSAT (JL) = 0.0_JPRB
    ZTARG(JL) = ZTARG(JL) + ZFOEEW (JL)*R2ES*&
     & Z3ES(JL)*(RTT-Z4ES(JL))*&
     & EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/&
     & (ZTARG5(JL)-Z4ES(JL)))/          &
     & (ZTARG5(JL)-Z4ES(JL))**2  
    ZFOEEW (JL) = 0.0_JPRB
    ZTP1 (JL,JK) = ZTP1 (JL,JK) + ZTARG (JL)
    ZTARG (JL) = 0.0_JPRB
  ENDDO

!DIR$    IVDEP
!OCL NOVREC
  DO JL=KIDIA,KFDIA
    ZCOND1 (JL) = ZCOND1 (JL) - ZQP1 (JL,JK)
    ZCOND1 (JL) = ZCOND1 (JL) + ZALDCP(JL)*ZTP1 (JL,JK)
    ZQSAT5T(JL,JK)=ZQSAT55B(JL)
    ZCOR5T(JL,JK)=ZCOR55B(JL)
    Z2S5(JL)=Z2S55B(JL)
    ZQP1 (JL,JK) = ZQP1 (JL,JK) + ZCOND1 (JL)/&
     & (1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)/&
     & (1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))  
    ZQSAT (JL) = ZQSAT (JL) - ZCOND1 (JL)*&
     & (ZQ55B(JL)-ZQSAT5T(JL,JK))*ZCOR5T(JL,JK)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))**2  
    ZCOR (JL) = ZCOR (JL) - ZCOND1 (JL)*&
     & (ZQ55B(JL)-ZQSAT5T(JL,JK))*ZQSAT5T(JL,JK)*Z2S5(JL)/&
     & (1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))**2  
    Z2S (JL) = Z2S (JL) - ZCOND1 (JL)*&
     & (ZQ55B(JL)-ZQSAT5T(JL,JK))*ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)/&
     & (1.0_JPRB+ZQSAT5T(JL,JK)*ZCOR5T(JL,JK)*Z2S5(JL))**2  
    ZCOND1 (JL) = 0.0_JPRB
    ZTARG5(JL)=ZTARG55B(JL)
    ZTARG(JL) = ZTARG(JL) - 2.0_JPRB*Z2S (JL)*&
     & Z5ALCP(JL)/(ZTARG5(JL)-Z4ES(JL))**3  
    Z2S (JL) = 0.0_JPRB
    ZQSAT5T(JL,JK)=ZQSAT55D(JL)
    ZCOR (JL) = ZCOR (JL) + ZQSAT (JL)*ZQSAT5T(JL,JK)
    ZQSAT (JL) = ZQSAT (JL)*ZCOR5T(JL,JK)
    ZQSAT(JL) = ZQSAT(JL) + ZCOR(JL)*RETV/(1.0_JPRB-RETV*ZQSAT5T(JL,JK))**2
    ZCOR(JL) = 0.0_JPRB
    IF (LLTEST2(JL)) THEN
      ZQSAT (JL)=0.0_JPRB
    ENDIF
    ZFOEEW (JL) = ZFOEEW (JL) + ZQSAT (JL)*ZQP5(JL)
    ZFOEEW5T(JL,JK)=ZFOEEW55B(JL)
    ZQP (JL) = ZQP (JL) + ZQSAT (JL)*ZFOEEW5T(JL,JK)
    ZQSAT (JL) = 0.0_JPRB
    ZTARG(JL) = ZTARG(JL) + ZFOEEW (JL)*R2ES*&
     & Z3ES(JL)*(RTT-Z4ES(JL))*&
     & EXP(Z3ES(JL)*(ZTARG5(JL)-RTT)/&
     & (ZTARG5(JL)-Z4ES(JL)))/          &
     & (ZTARG5(JL)-Z4ES(JL))**2  
    ZFOEEW (JL) = 0.0_JPRB
    ZTP1 (JL,JK) = ZTP1 (JL,JK) + ZTARG (JL)
    ZTARG (JL) = 0.0_JPRB
    ZPP(JL) = ZPP(JL) - ZQP(JL)/ZPP5(JL)**2
    ZQP(JL) = 0.0_JPRB
  ENDDO
!----- end fo inlined cuadjtqsad
  DO JL=KIDIA,KFDIA    

    ZDTDT = 0.0_JPRB 
    ZDQDT = 0.0_JPRB 

! first guess T and Q

    ZQP1 (JL,JK) = ZQP1 (JL,JK)+ZQOLD (JL)
    ZQOLD (JL) = 0.0_JPRB
    PAPP1 (JL,JK) = PAPP1 (JL,JK)+ZPP (JL)
    ZPP (JL) = 0.0_JPRB

    ZDQDT = ZDQDT + PTSPHY * ZQP1 (JL,JK)
    ZDTDT = ZDTDT + PTSPHY * ZTP1 (JL,JK)

!   Incrementation of T and Q 

! T tendency
    ZGDP (JL) = ZGDP (JL) - ZDTDT  & 
            & * (ZLVDCP5(JL,JK)*ZEVAPR5(JL,JK)+ZLSDCP5(JL,JK)*ZEVAPS5(JL,JK) &
            & +  PLUDE5(JL,JK)*(ZFWAT5(JL,JK)*ZLVDCP5(JL,JK) &
            & + (1.0_JPRB-ZFWAT5(JL,JK))*ZLSDCP5(JL,JK))&
            & - (ZLSDCP5(JL,JK)-ZLVDCP5(JL,JK))*ZRFREEZE15(JL,JK))
    ZCONDL(JL,JK) = ZCONDL(JL,JK) + ZDTDT * ZLVDCP5(JL,JK)
    ZCONDI(JL,JK) = ZCONDI(JL,JK) + ZDTDT * ZLSDCP5(JL,JK)
    ZEVAPR(JL,JK) = ZEVAPR(JL,JK) - ZDTDT * ZLVDCP5(JL,JK)*ZGDP5(JL,JK)
    ZEVAPS(JL,JK) = ZEVAPS(JL,JK) - ZDTDT * ZLSDCP5(JL,JK)*ZGDP5(JL,JK)
    ZLVDCP(JL,JK) = ZLVDCP(JL,JK) + ZDTDT *(ZCONDL15(JL,JK)-ZEVAPR5(JL,JK)*ZGDP5(JL,JK))
    ZLSDCP(JL,JK) = ZLSDCP(JL,JK) + ZDTDT *(ZCONDI15(JL,JK)-ZEVAPS5(JL,JK)*ZGDP5(JL,JK))
    PLUDE(JL,JK)  = PLUDE(JL,JK)  - ZDTDT * ZGDP5(JL,JK) &
                & * (ZFWAT5(JL,JK)*ZLVDCP5(JL,JK) &
                & + (1.0_JPRB-ZFWAT5(JL,JK))*ZLSDCP5(JL,JK))
    ZLVDCP(JL,JK) = ZLVDCP(JL,JK) - ZDTDT * PLUDE5(JL,JK)*ZGDP5(JL,JK) &
                & * ZFWAT5(JL,JK) 
    ZLSDCP(JL,JK) = ZLSDCP(JL,JK) - ZDTDT * PLUDE5(JL,JK)*ZGDP5(JL,JK) &
                & * (1.0_JPRB-ZFWAT5(JL,JK))
    ZFWAT(JL) = ZFWAT(JL) - ZDTDT * PLUDE5(JL,JK)*ZGDP5(JL,JK) &
            & * (ZLVDCP5(JL,JK)-ZLSDCP5(JL,JK)) 
    ZLSDCP(JL,JK) = ZLSDCP(JL,JK) + ZDTDT * ZRFREEZE15(JL,JK)*ZGDP5(JL,JK)
    ZLVDCP(JL,JK) = ZLVDCP(JL,JK) - ZDTDT * ZRFREEZE15(JL,JK)*ZGDP5(JL,JK)
    ZRFREEZE (JL,JK) = ZRFREEZE (JL,JK) + ZDTDT *(ZLSDCP5(JL,JK)-ZLVDCP5(JL,JK)) &
                   & * ZGDP5(JL,JK)
    ZDTDT=0.0_JPRB

! q tendency
    ZGDP(JL) = ZGDP(JL) + ZDQDT *(PLUDE5(JL,JK)+ZEVAPR5(JL,JK)+ZEVAPS5(JL,JK))
    PLUDE(JL,JK)  = PLUDE(JL,JK)  + ZDQDT * ZGDP5(JL,JK)
    ZEVAPR(JL,JK) = ZEVAPR(JL,JK) + ZDQDT * ZGDP5(JL,JK)
    ZEVAPS(JL,JK) = ZEVAPS(JL,JK) + ZDQDT * ZGDP5(JL,JK)
    ZCONDL(JL,JK) = ZCONDL(JL,JK) - ZDQDT 
    ZCONDI(JL,JK) = ZCONDI(JL,JK) - ZDQDT 
    ZDQDT=0.0_JPRB
  ENDDO

  DO JL=KIDIA,KFDIA
    ZSN     = 0.0_JPRB
    ZRN     = 0.0_JPRB
    ZOEALFA = 0.0_JPRB
    ZPRR    = 0.0_JPRB
    ZPRS    = 0.0_JPRB
    ZLNEW   = 0.0_JPRB
    ZINEW   = 0.0_JPRB
    ZCLDL   = 0.0_JPRB
    ZCLDI   = 0.0_JPRB
    ZDL     = 0.0_JPRB
    ZDI     = 0.0_JPRB

    ZPRTOT  = 0.0_JPRB
    ZPRECLR = 0.0_JPRB
    ZQE     = 0.0_JPRB
    ZBETA   = 0.0_JPRB
    ZB      = 0.0_JPRB
    ZDPR    = 0.0_JPRB
    ZFWATR  = 0.0_JPRB
    ZDR     = 0.0_JPRB

!   Precip evaporation

    LLO2=ZPRTOT5(JL,JK)>ZEPS2 .AND. ZCOVPCLR5(JL,JK)>ZEPS2 &
     & .AND. (LEVAPLS2 .OR. LDRAIN1D)

    IF (LLO2) THEN

! ice proportion
      ZEVAPS (JL,JK) = ZEVAPS (JL,JK) - ZSFLN (JL)
      ZSFLN(JL) = ZSFLN(JL)+ZDPR5(JL,JK)*ZEVAPS (JL,JK)/ZPRTOT5(JL,JK)
      ZDPR = ZDPR+ZSFLN25(JL,JK)*ZEVAPS (JL,JK)/ZPRTOT5(JL,JK)
      ZPRTOT = ZPRTOT-ZDPR5(JL,JK)*ZSFLN25(JL,JK)*ZEVAPS (JL,JK)/ZPRTOT5(JL,JK)**2  
      ZEVAPS (JL,JK) = 0.0_JPRB

! warm proportion
      ZEVAPR (JL,JK) = ZEVAPR (JL,JK) - ZRFLN (JL)
      ZRFLN(JL) = ZRFLN(JL)+ZDPR5(JL,JK)*ZEVAPR (JL,JK)/ZPRTOT5(JL,JK)
      ZDPR = ZDPR+ZRFLN25(JL,JK)*ZEVAPR (JL,JK)/ZPRTOT5(JL,JK)
      ZPRTOT = ZPRTOT-ZDPR5(JL,JK)*ZRFLN25(JL,JK)*ZEVAPR (JL,JK)/ZPRTOT5(JL,JK)**2  
      ZEVAPR (JL,JK) = 0.0_JPRB

! take away from clr sky flux
      ZCOVPTOT(JL) = ZCOVPTOT(JL)+PCOVPTOT(JL,JK)
      PCOVPTOT(JL,JK) = 0.0_JPRB
      IF (ZPRECLR5(JL,JK) <= 0.0_JPRB) THEN !reset
        PCLC(JL,JK) = PCLC(JL,JK)+ZCOVPTOT (JL)
        ZCOVPTOT (JL) = 0.0_JPRB
      ENDIF
      ZDPR = ZDPR-ZPRECLR

      IF (ZDPR15(JL,JK) > ZPRECLR15(JL,JK)) THEN
        ZPRECLR = ZPRECLR+ZDPR
        ZDPR = 0.0_JPRB
      ENDIF

      ZB = ZB+ZCOVPCLR5(JL,JK)*ZDPR/ZDTGDP5(JL,JK)
      ZCOVPCLR(JL) = ZCOVPCLR(JL)+ZB5(JL,JK)*ZDPR/ZDTGDP5(JL,JK)
      ZDTGDP(JL) = ZDTGDP(JL)-ZCOVPCLR5(JL,JK)*ZB5(JL,JK)*ZDPR &
       & / ZDTGDP5(JL,JK)**2  
      
      PAPHP1(JL,JK+1) = PAPHP1(JL,JK+1)-PTSPHY*RG*ZDTGDP (JL) &
       & / (PAPHP15(JL,JK+1)-PAPHP15(JL,JK))**2  
      PAPHP1(JL,JK) = PAPHP1(JL,JK)+PTSPHY*RG*ZDTGDP (JL) &
       & / (PAPHP15(JL,JK+1)-PAPHP15(JL,JK))**2  
      ZDTGDP (JL) = 0.0_JPRB

!     exact solution:

!      PQS(JL,JK) = PQS(JL,JK)-ZEXP5(JL,JK)*ZB/ZCORQS5(JL,JK)
!      ZQE = ZQE+ZEXP5(JL,JK)*ZB/ZCORQS5(JL,JK)
!      ZCORQS(JL) = ZCORQS(JL)+ZEXP5(JL,JK)*(PQS5(JL,JK)-ZQE5(JL,JK)) &
!       &         * PTSPHY * ZBETA5(JL,JK)*ZB/ZCORQS5(JL,JK)
!      ZBETA = ZBETA+ZEXP5(JL,JK)*(PQS5(JL,JK)-ZQE5(JL,JK))*PTSPHY*ZB
!      ZCORQS(JL) = ZCORQS(JL)+ZEXP5(JL,JK)*(PQS5(JL,JK)-ZQE5(JL,JK)) &
!       &         * ZB / ZCORQS5(JL,JK)**2
!      PQS(JL,JK) = PQS(JL,JK)+ZB/ZCORQS5(JL,JK)
!      ZQE = ZQE-ZB/ZCORQS5(JL,JK)
!      ZCORQS(JL) = ZCORQS(JL)-(PQS5(JL,JK)-ZQE5(JL,JK))*ZB &
!       &         / ZCORQS5(JL,JK)**2

!     implicit solution:

      ZBETA = ZBETA+PTSPHY*(PQS5(JL,JK)-ZQE5(JL,JK))*ZB &
       & / (1.0_JPRB+ZBETA5(JL,JK)*PTSPHY*ZCORQS5(JL,JK))  
      PQS(JL,JK) = PQS(JL,JK)+PTSPHY*ZBETA5(JL,JK)*ZB &
       & / (1.0_JPRB+ZBETA5(JL,JK)*PTSPHY*ZCORQS5(JL,JK))  
      ZQE = ZQE-PTSPHY*ZBETA5(JL,JK)*ZB &
       & / (1.0_JPRB+ZBETA5(JL,JK)*PTSPHY*ZCORQS5(JL,JK))  
      ZCORQS(JL) = ZCORQS(JL)-(PTSPHY**2)*ZBETA5(JL,JK) &
       & * (PQS5(JL,JK)-ZQE5(JL,JK))*ZBETA5(JL,JK)*ZB &
       & / (1.0_JPRB+ZBETA5(JL,JK)*PTSPHY*ZCORQS5(JL,JK))**2  
      ZBETA = ZBETA-(PTSPHY**2)*ZBETA5(JL,JK) &
       & * (PQS5(JL,JK)-ZQE5(JL,JK))*ZCORQS5(JL,JK)*ZB &
       & / (1.0_JPRB+ZBETA5(JL,JK)*PTSPHY*ZCORQS5(JL,JK))**2  

!     This is the humidity in the moistest zcovpclr region

      ZXX5 = 0.5777_JPRB*(RG*RPECONS/5.09E-3_JPRB) &
       & * (5.09E-3_JPRB*ZCOVPCLR5(JL,JK)/(ZPRECLR15(JL,JK) &
       & * SQRT(PAPP15(JL,JK)/PAPHP15(JL,KLEV+1))))**0.4223_JPRB  
      ZPRECLR = ZPRECLR+ZXX5*SQRT(PAPP15(JL,JK)/PAPHP15(JL,KLEV+1)) &
       & * ZBETA/ZCOVPCLR5(JL,JK)  
      PAPP1(JL,JK) = PAPP1(JL,JK)+(ZXX5*0.5_JPRB*ZPRECLR15(JL,JK)*ZBETA &
       & / SQRT(PAPP15(JL,JK)*PAPHP15(JL,KLEV+1))) &
       & / ZCOVPCLR5(JL,JK)  
      PAPHP1(JL,KLEV+1) = PAPHP1(JL,KLEV+1) &
       & -(ZXX5*0.5_JPRB*ZPRECLR15(JL,JK) &
       & * SQRT(PAPP15(JL,JK)/PAPHP15(JL,KLEV+1)) &
       & * ZBETA/PAPHP15(JL,KLEV+1)) &
       & / ZCOVPCLR5(JL,JK)  
      ZCOVPCLR(JL) = ZCOVPCLR(JL)-ZXX5*ZPRECLR15(JL,JK) &
       & * SQRT(PAPP15(JL,JK)/PAPHP15(JL,KLEV+1)) &
       & * ZBETA/ZCOVPCLR5(JL,JK)**2  

      PQS(JL,JK) = PQS(JL,JK)+ZQE
      ZCOVPCLR(JL) = ZCOVPCLR(JL)-(PQS5(JL,JK)-ZQLIM5(JL,JK))*ZQE &
       & / (1.0_JPRB-PCLC5(JL,JK))**2  
      PQS(JL,JK) = PQS(JL,JK)-ZCOVPCLR5(JL,JK)*ZQE &
       & / (1.0_JPRB-PCLC5(JL,JK))**2  
      ZQLIM(JL) = ZQLIM(JL)+ZCOVPCLR5(JL,JK)*ZQE &
       & / (1.0_JPRB-PCLC5(JL,JK))**2  
      PCLC(JL,JK) = PCLC(JL,JK)-2.0_JPRB*(PQS5(JL,JK)-ZQLIM5(JL,JK)) &
       & * ZCOVPCLR5(JL,JK)*ZQE &
       & / (1.0_JPRB-PCLC5(JL,JK))**3  

      ZCOVPCLR(JL) = ZCOVPCLR(JL)+ZPRTOT5(JL,JK)*ZPRECLR &
       & / ZCOVPTOT15(JL,JK)  
      ZPRTOT = ZPRTOT+ZCOVPCLR5(JL,JK)*ZPRECLR &
       & / ZCOVPTOT15(JL,JK)  
      ZCOVPTOT(JL) = ZCOVPTOT(JL)-ZPRTOT5(JL,JK)*ZCOVPCLR5(JL,JK) &
       & * ZPRECLR / ZCOVPTOT15(JL,JK)**2  
    ENDIF

!    New precipitation

    ZRFLN (JL) = ZRFLN (JL)+ZPRTOT
    ZSFLN (JL) = ZSFLN (JL)+ZPRTOT

    ZSN = ZSN+ZSFLN(JL)
    ZRN = ZRN+ZRFLN(JL)

    ZFWATR = ZFWATR-ZDR15(JL,JK)*ZSN
    ZDR    = ZDR   +(1.0_JPRB-ZFWATR15(JL,JK))*ZSN
    ZFWATR = ZFWATR+ZDR15(JL,JK)*ZRN
    ZDR    = ZDR   +ZFWATR15(JL,JK)*ZRN

! Update rain fraction and freezing.
! Note: impact of new temperature ZTP1 on ZFWAT is neglected here.
    IF (ZTP15(JL,JK) < RTT) THEN
      ZDP(JL,JK) = ZDP(JL,JK) + ZRFREEZE(JL,JK) * ZCONS2*ZPRR5(JL,JK)
      ZPRR       = ZPRR       + ZRFREEZE(JL,JK) * ZCONS2*ZDP5(JL,JK)
      ZRFREEZE (JL,JK)=0.0_JPRB
    ENDIF 
    ZFWATR=0.0_JPRB

    ZPRR       = ZPRR       + ZCONS2*ZDP5(JL,JK)*ZDR 
    ZPRS       = ZPRS       + ZCONS2*ZDP5(JL,JK)*ZDR 
    ZDP(JL,JK) = ZDP(JL,JK) + ZCONS2*(ZPRR5(JL,JK)+ZPRS5(JL,JK))*ZDR
    ZDR = 0.0_JPRB

!    Diagnostic calculation of rain production from cloud ice

    IF (PCLC5(JL,JK) > ZEPS2) THEN
      IF (LEVAPLS2 .OR. LDRAIN1D) THEN
        ZLCRIT = 1.E-04_JPRB
      ELSE
        ZLCRIT = RCLCRIT*2._JPRB
      ENDIF
      ZPRS = ZPRS - ZQIWC(JL,JK)

      ZQIWC(JL,JK) = ZQIWC(JL,JK) + ZPRS
      ZINEW        = ZINEW        - ZPRS

      PCLC(JL,JK) = PCLC(JL,JK) + ZINEW * ZCLDI5(JL,JK)*ZEXPDI5(JL,JK)
      ZCLDI       = ZCLDI       + ZINEW * PCLC5(JL,JK)*ZEXPDI5(JL,JK)
      ZDI         = ZDI         - ZINEW * PCLC5(JL,JK)*ZCLDI5(JL,JK)*ZEXPDI5(JL,JK)

!    regularization of ZD
      IF (LREGCL) THEN
        ZTP1(JL,JK) = ZTP1(JL,JK) + ZCKCODTIA*ZEXP15(JL,JK) &
                  & *(1.0_JPRB-ZEXP25(JL,JK))*0.025_JPRB*ZDI
        ZCLDI = ZCLDI + (ZCKCODTIA*ZEXP15(JL,JK)*ZEXP25(JL,JK)*2.0_JPRB &
            & * ZCLDI5(JL,JK)/ZLCRIT**2)*ZDI  
      ELSE
        ZTP1(JL,JK) = ZTP1(JL,JK) + ZCKCODTI*ZEXP15(JL,JK) &
                  & *(1.0_JPRB-ZEXP25(JL,JK))*0.025_JPRB*ZDI
        ZCLDI = ZCLDI + (ZCKCODTI*ZEXP15(JL,JK)*ZEXP25(JL,JK)*2.0_JPRB &
            & * ZCLDI5(JL,JK)/ZLCRIT**2)*ZDI  
      ENDIF
!    end of regularization
    
      ZQIWC (JL,JK) = ZQIWC (JL,JK) + ZCLDI/PCLC5(JL,JK)
      PCLC(JL,JK) = PCLC(JL,JK) - ZQIWC15(JL,JK)*ZCLDI/PCLC5(JL,JK)**2
    ENDIF
    ZPRS = 0.0_JPRB

!    Diagnostic calculation of rain production from cloud liquid water

    IF (PCLC5(JL,JK) > ZEPS2) THEN
      IF (LEVAPLS2 .OR. LDRAIN1D) THEN
        ZLCRIT = 1.9_JPRB*RCLCRIT
      ELSE
        ZLCRIT = RCLCRIT*2._JPRB
      ENDIF
      ZPRR = ZPRR - ZQLWC (JL,JK)

      ZQLWC (JL,JK) = ZQLWC (JL,JK) + ZPRR
      ZLNEW = ZLNEW - ZPRR

      PCLC(JL,JK) = PCLC(JL,JK) + ZLNEW * ZCLDL5(JL,JK)*ZEXPDL5(JL,JK)
      ZCLDL       = ZCLDL       + ZLNEW * PCLC5(JL,JK)*ZEXPDL5(JL,JK)
      ZDL         = ZDL         - ZLNEW * PCLC5(JL,JK)*ZCLDL5(JL,JK)*ZEXPDL5(JL,JK)

!    regularization of ZD
      IF (LREGCL) THEN
        ZCLDL = ZCLDL + (2.0_JPRB*ZCKCODTLA/ZLCRIT**2) &
            & * ZEXP35(JL,JK)*ZCLDL5(JL,JK)*ZDL  
      ELSE
        ZCLDL = ZCLDL + (2.0_JPRB*ZCKCODTL/ZLCRIT**2) &
            & * ZEXP35(JL,JK)*ZCLDL5(JL,JK)*ZDL 
      ENDIF
!    end of regularization

      ZQLWC (JL,JK) = ZQLWC (JL,JK) + ZCLDL/PCLC5(JL,JK)
      PCLC(JL,JK) = PCLC(JL,JK) - ZQLWC15(JL,JK)*ZCLDL/PCLC5(JL,JK)**2
    ENDIF
    ZPRR = 0.0_JPRB

  ENDDO

!    Melting of incoming snow

  DO JL=KIDIA,KFDIA
    ZSNMLT = 0.0_JPRB
    ZCONS  = 0.0_JPRB
    ZZ2S   = 0.0_JPRB

    IF (ZSFL5(JL,JK) /= 0.0_JPRB) THEN
      ZSNMLT = ZSNMLT-ZTP1 (JL,JK)/ZCONS5(JL,JK)
      ZCONS = ZCONS+(ZTP1 (JL,JK)*ZSNMLT5(JL,JK))/ZCONS5(JL,JK)**2
      
      ZSFL (JL) = ZSFL (JL)+ZSFLN (JL)
      ZSNMLT = ZSNMLT-ZSFLN (JL)
      ZSFLN (JL) = 0.0_JPRB

      ZRFL (JL) = ZRFL (JL)+ZRFLN (JL)
      ZSNMLT = ZSNMLT+ZRFLN (JL)
      ZRFLN (JL) = 0.0_JPRB
      
      IF (ZSFL5(JL,JK) <= ZZ2S5(JL,JK)) THEN
        ZSFL (JL) = ZSFL (JL)+ZSNMLT
      ELSE
        ZZ2S = ZZ2S+ZSNMLT
      ENDIF
        
      IF ((ZTP25(JL,JK)-ZMELTP2) > 0.0_JPRB) THEN
        ZTP1 (JL,JK) = ZTP1 (JL,JK)+ZCONS5(JL,JK)*ZZ2S
        ZCONS = ZCONS+(ZTP25(JL,JK)-ZMELTP2)*ZZ2S
      ENDIF

      ZDP(JL,JK) = ZDP(JL,JK)+ZCONS2*ZCONS/ZLFDCP5(JL,JK)
      ZLFDCP(JL,JK) = ZLFDCP(JL,JK) &
       & - ZCONS2*ZDP5(JL,JK)*ZCONS/ZLFDCP5(JL,JK)**2  
    ELSE
      ZSFL (JL) = ZSFL (JL)+ZSFLN (JL)
      ZSFLN (JL) = 0.0_JPRB

      ZRFL (JL) = ZRFL (JL)+ZRFLN (JL)
      ZRFLN (JL) = 0.0_JPRB
    ENDIF
  ENDDO

!       3.1   INITIALIZATION

! Calculate precipitation overlap. 
! Simple form based on Maximum Overlap.

  DO JL=KIDIA,KFDIA
    IF (ZCOVPCLR15(JL,JK) < 0.0_JPRB) THEN
      ZCOVPCLR(JL) = 0.0_JPRB
    ENDIF
    ZCOVPTOT(JL) = ZCOVPTOT(JL) + ZCOVPCLR(JL)
    PCLC(JL,JK)  = PCLC(JL,JK)  - ZCOVPCLR(JL)
    ZCOVPCLR(JL) = 0.0_JPRB

    IF (PCLC5(JL,JK) > ZCOVPTOT5(JL,JK-1)) THEN ! total rain frac
      PCLC(JL,JK) = PCLC(JL,JK)+ZCOVPTOT(JL)
      ZCOVPTOT(JL) = 0.0_JPRB
    ENDIF

  ENDDO

! New cloud liquid/ice contents and condensation rates (liquid/ice)

  DO JL=KIDIA,KFDIA
    ZQC(JL) = 0.0_JPRB

    ZQIWC(JL,JK) = ZQIWC(JL,JK) + ZCONDI(JL,JK) * ZQTMST
    ZI(JL,JK)    = ZI(JL,JK)    - ZCONDI(JL,JK) * ZQTMST
    ZCONDI(JL,JK) = 0.0_JPRB

    ZQLWC(JL,JK) = ZQLWC(JL,JK) + ZCONDL(JL,JK) * ZQTMST
    ZL(JL,JK)    = ZL(JL,JK)    - ZCONDL(JL,JK) * ZQTMST
    ZCONDL(JL,JK) = 0.0_JPRB

    ZQC(JL)   = ZQC(JL)   + ZQIWC(JL,JK)*(1.0_JPRB-ZFWAT5(JL,JK))
    ZFWAT(JL) = ZFWAT(JL) - ZQIWC(JL,JK)*ZQC35(JL,JK)
    ZQIWC(JL,JK) = 0.0_JPRB

    ZQC(JL)   = ZQC(JL)   + ZQLWC(JL,JK)*ZFWAT5(JL,JK)
    ZFWAT(JL) = ZFWAT(JL) + ZQLWC(JL,JK)*ZQC35(JL,JK)
    ZQLWC(JL,JK) = 0.0_JPRB
  ENDDO

! Add compensating subsidence component

  DO JL=KIDIA,KFDIA
    ZDQC     = 0.0_JPRB
    ZDQSDZ   = 0.0_JPRB
    DTDZMO   = 0.0_JPRB
    ZLDCP    = 0.0_JPRB
    ZRODQSDP = 0.0_JPRB
    ZRHO     = 0.0_JPRB
    ZESDP    = 0.0_JPRB
    ZFOEEW(JL) = 0.0_JPRB

    ZDQC = ZDQC - ZQC(JL)
    
    IF (LLO3(JL,JK)) THEN
! Regularization
      IF (LREGCL) ZDQC = ZDQC * 0.1_JPRB

      ZDQSDZ      = ZDQSDZ      + ZDQC * PTSPHY*(PMFU5(JL,JK)+PMFD5(JL,JK))*ZFAC4(JL,JK)
      PMFU(JL,JK) = PMFU(JL,JK) + ZDQC * PTSPHY*ZDQSDZ5(JL,JK)*ZFAC4(JL,JK)
      PMFD(JL,JK) = PMFD(JL,JK) + ZDQC * PTSPHY*ZDQSDZ5(JL,JK)*ZFAC4(JL,JK)
      ZRHO        = ZRHO        - ZDQC * ZDQC5(JL,JK)*ZFAC4(JL,JK)
    ELSE
      ZQC (JL) = ZQC (JL) + ZDQC
    ENDIF
    ZDQC = 0.0_JPRB
   
    DTDZMO        = DTDZMO        + ZDQSDZ * ZDQSDTEMP5(JL,JK)
    ZDQSDTEMP(JL) = ZDQSDTEMP(JL) + ZDQSDZ * DTDZMO5(JL,JK)
    ZRODQSDP      = ZRODQSDP      - ZDQSDZ * RG
    ZDQSDZ = 0.0_JPRB
     
    ZLDCP         = ZLDCP         - DTDZMO * ( RG*ZRODQSDP5(JL,JK) &
                & + DTDZMO5(JL,JK)*ZDQSDTEMP5(JL,JK) ) * ZFAC3(JL,JK)
    ZRODQSDP      = ZRODQSDP      - DTDZMO * RG*ZLDCP5(JL,JK)*ZFAC3(JL,JK)
    ZDQSDTEMP(JL) = ZDQSDTEMP(JL) - DTDZMO * DTDZMO5(JL,JK)*ZLDCP5(JL,JK)*ZFAC3(JL,JK)
    DTDZMO = 0.0_JPRB

    ZFWAT(JL)     = ZFWAT(JL)     + ZLDCP * (ZLVDCP5(JL,JK)-ZLSDCP5(JL,JK))
    ZLVDCP(JL,JK) = ZLVDCP(JL,JK) + ZLDCP * ZFWAT5(JL,JK)
    ZLSDCP(JL,JK) = ZLSDCP(JL,JK) + ZLDCP * (1.0_JPRB-ZFWAT5(JL,JK))
    ZLDCP = 0.0_JPRB 

    ZRHO = ZRHO - ZRODQSDP * PQS5(JL,JK)*ZFAC2(JL,JK)
    PQS(JL,JK) = PQS(JL,JK) - ZRODQSDP * ZRHO5(JL,JK)*ZFAC2(JL,JK)
    PAPP1(JL,JK) = PAPP1(JL,JK) + ZRODQSDP * ZRHO5(JL,JK)*PQS5(JL,JK)*ZFAC2(JL,JK)**2
    ZFOEEW(JL) = ZFOEEW(JL) - ZRODQSDP * ZRHO5(JL,JK)*PQS5(JL,JK)*RETV*ZFAC2(JL,JK)**2
    ZRODQSDP = 0.0_JPRB 

    PAPP1(JL,JK) = PAPP1(JL,JK) + ZRHO * ZFAC1(JL,JK)
    ZTP1(JL,JK)  = ZTP1(JL,JK)  - ZRHO * PAPP15(JL,JK)/ZTP25(JL,JK)*ZFAC1(JL,JK)
    ZRHO = 0.0_JPRB
  ENDDO

! Add convective component

  DO JL=KIDIA,KFDIA
    IF (JK<KLEV) THEN
      LLO1=ZLUDE5(JL,JK)>=RLMIN.AND.PLU5(JL,JK+1)>=ZEPS2
    ELSE
      LLO1=.FALSE.
    ENDIF
    IF (LLO1) THEN
      ZLUDE(JL,JK) = ZLUDE(JL,JK) + ZQC(JL)
      ZLUDE(JL,JK) = ZLUDE(JL,JK) &
       & + ((1.0_JPRB-ZCLC5(JL,JK))/PLU5(JL,JK+1)) &
       & * EXP(-ZLUDE5(JL,JK)/PLU5(JL,JK+1))*PCLC (JL,JK)  
      PLU(JL,JK+1) = PLU(JL,JK+1) &
       & -((1.0_JPRB-ZCLC5(JL,JK))*ZLUDE5(JL,JK)/PLU5(JL,JK+1)**2) &
       & * EXP(-ZLUDE5(JL,JK)/PLU5(JL,JK+1))*PCLC (JL,JK)  
      PCLC (JL,JK)=PCLC(JL,JK) &
       & *(1.0_JPRB-(1.0_JPRB-EXP(-ZLUDE5(JL,JK)/PLU5(JL,JK+1))))  
    ENDIF
 
    PLUDE(JL,JK) = PLUDE(JL,JK)+PTSPHY*ZGDP5(JL,JK)*ZLUDE (JL,JK)
    ZGDP(JL) = ZGDP(JL)+PTSPHY*PLUDE5(JL,JK)*ZLUDE (JL,JK)
    ZLUDE (JL,JK) = 0.0_JPRB

    PAPHP1(JL,JK+1) = PAPHP1(JL,JK+1)-RG*ZGDP (JL) &
     & / (PAPHP15(JL,JK+1)-PAPHP15(JL,JK))**2  
    PAPHP1(JL,JK) = PAPHP1(JL,JK)+RG*ZGDP (JL) &
     & / (PAPHP15(JL,JK+1)-PAPHP15(JL,JK))**2  
    ZGDP (JL) = 0.0_JPRB
  ENDDO

! Simple UNIFORM distribution of total water from Letreut & Li (90)

  DO JL=KIDIA,KFDIA
    ZQPD = 0.0_JPRB
    ZQCD = 0.0_JPRB
    ZQT  = 0.0_JPRB
    ZQSAT(JL) = 0.0_JPRB

    IF (ZQT5(JL,JK) <= ZQCRIT5(JL,JK)) THEN
      ZQC (JL) = 0.0_JPRB
      PCLC (JL,JK) = 0.0_JPRB 
    ELSE IF (ZQT5(JL,JK) >= ZQSAT5(JL,JK)) THEN
      ZQSAT(JL) = ZQSAT(JL)+(1.0_JPRB-ZSCALM(JK))*ZQC (JL)
      ZQCRIT(JL) = ZQCRIT(JL)-(1.0_JPRB-ZSCALM(JK))*ZQC (JL)
      ZQC (JL) = 0.0_JPRB
      PCLC (JL,JK) = 0.0_JPRB 
    ELSE 
      ZQPD = ZQPD+ZSCALM(JK)*ZQC (JL)*ZCLC5(JL,JK)**2
      ZQCD = ZQCD+(1.0_JPRB-ZSCALM(JK))*ZQC (JL)*ZCLC5(JL,JK)**2
      PCLC(JL,JK) = PCLC(JL,JK)+(ZSCALM(JK)*ZQPD5(JL,JK) &
       & + (1.0_JPRB-ZSCALM(JK))*ZQCD5(JL,JK)) &
       & * 2.0_JPRB*ZCLC5(JL,JK)*ZQC (JL)  
      ZQC (JL) = 0.0_JPRB

! regularization of cloud fraction
      IF (LREGCL) THEN
        ZRAT=ZQPD5(JL,JK)/ZQCD5(JL,JK)
        ZYYY = MIN(0.3_JPRB,3.5_JPRB*SQRT(ZRAT*(1.0_JPRB-ZSCALM(JK)*(1.0_JPRB-ZRAT))**3) &
           & /(1.0_JPRB-ZSCALM(JK)))
        PCLC (JL,JK) = ZYYY * PCLC (JL,JK) 
      ENDIF
! end of regularization

      ZQPD = ZQPD - (0.5_JPRB/ZSQRT5(JL,JK))*PCLC(JL,JK) &
       & / (ZQCD5(JL,JK)-ZSCALM(JK)*(ZQT5(JL,JK)-ZQCRIT5(JL,JK)))  
      ZQCD = ZQCD + (0.5_JPRB/ZSQRT5(JL,JK))*(ZQPD5(JL,JK)*PCLC(JL,JK)) &
       & / (ZQCD5(JL,JK)-ZSCALM(JK)*(ZQT5(JL,JK)-ZQCRIT5(JL,JK)))**2  
      ZQT  = ZQT - (0.5_JPRB/ZSQRT5(JL,JK)) &
       & * (ZQPD5(JL,JK)*ZSCALM(JK)*PCLC(JL,JK)) &
       & / (ZQCD5(JL,JK)-ZSCALM(JK)*(ZQT5(JL,JK)-ZQCRIT5(JL,JK)))**2  
      ZQCRIT(JL) = ZQCRIT(JL) + (0.5_JPRB/ZSQRT5(JL,JK)) &
       & * (ZQPD5(JL,JK)*ZSCALM(JK)*PCLC(JL,JK)) &
       & / (ZQCD5(JL,JK)-ZSCALM(JK)*(ZQT5(JL,JK)-ZQCRIT5(JL,JK)))**2  
      PCLC (JL,JK) = 0.0_JPRB 

      ZQSAT(JL)  = ZQSAT(JL)  + ZQCD
      ZQCRIT(JL) = ZQCRIT(JL) - ZQCD
      ZQSAT(JL)  = ZQSAT(JL)  + ZQPD
      ZQT        = ZQT        - ZQPD
    ENDIF

    ZQP1(JL,JK) = ZQP1(JL,JK) + ZQT
    ZL(JL,JK)   = ZL(JL,JK)   + ZQT
    ZI(JL,JK)   = ZI(JL,JK)   + ZQT
  ENDDO

  DO JL=KIDIA,KFDIA
    ZOEALFAW = 0.0_JPRB
    ZESDP    = 0.0_JPRB
    ZFACW    = 0.0_JPRB
    ZFACI    = 0.0_JPRB
    ZFAC     = 0.0_JPRB
    ZCOR(JL)     = 0.0_JPRB
    ZSUPSAT  = 0.0_JPRB

! set up critical value of humidity

    ZQSAT(JL) = ZQSAT(JL) + ZQCRIT(JL)*ZCRH2(JL,JK)
    ZQCRIT(JL) = 0.0_JPRB

    PQS(JL,JK) = PQS(JL,JK) + ZQSAT(JL)*ZSUPSAT5(JL,JK)
    ZSUPSAT    = ZSUPSAT    + ZQSAT(JL)*PQS5(JL,JK)
    ZQSAT(JL) = 0.0_JPRB

! Allow ice supersaturation at cold temperatures
    IF (ZTP25(JL,JK) < RTICE) THEN
      ZTP1(JL,JK) = ZTP1(JL,JK) - ZSUPSAT*3.E-03_JPRB
    ENDIF
    ZSUPSAT = 0.0_JPRB

! use clipped state

    IF (ZQP25(JL,JK) > PQS5(JL,JK)) THEN
      PQS (JL,JK) = PQS (JL,JK)+ZQLIM (JL)
    ELSE
      ZQP1(JL,JK) = ZQP1(JL,JK)+ZQLIM (JL)
    ENDIF
    ZQLIM (JL) = 0.0_JPRB

!-----------------------------------
! calculate dqs/dT correction factor
!-----------------------------------

    ZDQSDTEMP(JL) = ZDQSDTEMP(JL)+ZCONS3*ZCORQS(JL)
    ZCORQS(JL) = 0.0_JPRB

    PQS(JL,JK) = PQS(JL,JK)+ZFAC5(JL,JK)*ZCOR5(JL,JK)*ZDQSDTEMP(JL)
    ZCOR(JL) = ZCOR(JL)+ZFAC5(JL,JK)*PQS5(JL,JK)*ZDQSDTEMP(JL)
    ZFAC = ZFAC+ZCOR5(JL,JK)*PQS5(JL,JK)*ZDQSDTEMP(JL)
    ZDQSDTEMP(JL) = 0.0_JPRB

    ZESDP = ZESDP+RETV*ZCOR(JL)/(1.0_JPRB-RETV*ZESDP5(JL,JK))**2

    ZFACW     = ZFACW     + ZFWAT5(JL,JK)*ZFAC
    ZFWAT(JL) = ZFWAT(JL) + ZFACW5(JL,JK)*ZFAC
    ZFACI     = ZFACI     + (1.0_JPRB-ZFWAT5(JL,JK))*ZFAC
    ZFWAT(JL) = ZFWAT(JL) - ZFACI5(JL,JK)*ZFAC

    ZTP1(JL,JK) = ZTP1(JL,JK)-2.0_JPRB*R5IES*ZFACI &
              & / (ZTP25(JL,JK)-R4IES)**3  
    ZTP1(JL,JK) = ZTP1(JL,JK)-2.0_JPRB*R5LES*ZFACW &
              & / (ZTP25(JL,JK)-R4LES)**3  

    IF (ZESDP15(JL,JK) > ZQMAX) THEN
      ZESDP  = 0.0_JPRB
    ENDIF
    ZFOEEW(JL) = ZFOEEW(JL) + ZESDP/PAPP15(JL,JK)
    PAPP1(JL,JK) = PAPP1(JL,JK) - ZESDP*ZFOEEW5(JL,JK)/PAPP15(JL,JK)**2  
    
    IF (ZTP25(JL,JK) < RTT) THEN
      Z3ES(JL)=R3IES
      Z4ES(JL)=R4IES
    ELSE
      Z3ES(JL)=R3LES
      Z4ES(JL)=R4LES
    ENDIF
    ZTP1(JL,JK) = ZTP1(JL,JK)+ Z3ES(JL)*(RTT-Z4ES(JL))*ZFOEEW(JL) &
              & * ZFOEEW5(JL,JK)/(ZTP25(JL,JK)-Z4ES(JL))**2  
    
    IF (ZTP25(JL,JK) < RTT) THEN
      ZOEALFAW = ZOEALFAW + ZFWAT(JL)
    ENDIF
    ZFWAT(JL) = 0.0_JPRB

    ZTP1(JL,JK) = ZTP1(JL,JK)+0.545_JPRB*0.17_JPRB*ZOEALFAW &
     & / COSH(0.17_JPRB*(ZTP25(JL,JK)-RLPTRC))**2  

  ENDDO

ENDDO  !jk

!     ------------------------------------------------------------------

!*         2.2    INITIALIZATION OF CLOUD AND PRECIPITATION ARRAYS
!                 ------------------------------------------------

!       Set to zero precipitation fluxes at the top

DO JL=KIDIA,KFDIA
  PFPLSN (JL,1) = 0.0_JPRB
  PFPLSL (JL,1) = 0.0_JPRB
!  ZSFL (JL) = 0.0_JPRB
!  ZRFL (JL) = 0.0_JPRB
ENDDO

!       Clear cloud and freezing arrays

DO JK=1,KLEV
  DO JL=KIDIA,KFDIA
    PCOVPTOT(JL,JK) = 0.0_JPRB
!    ZRFREEZE (JL,JK) = 0.0_JPRB
    PCLC (JL,JK) = 0.0_JPRB
  ENDDO
ENDDO

!     --------------------------------------------------------------------

!*         2.1    COMPUTE CRITICAL RELATIVE HUMIDITY AND RELATIVE HUMIDITY
!                 --------------------------------------------------------

! thermodynamic constants

DO JK=KLEV,1,-1
  DO JL=KIDIA,KFDIA
    ZZZ = 0.0_JPRB

    ZZZ = ZZZ+RLVTT*ZLVDCP (JL,JK)
    ZLVDCP (JL,JK) = 0.0_JPRB
    ZZZ = ZZZ+RLSTT*ZLSDCP (JL,JK)
    ZLSDCP (JL,JK) = 0.0_JPRB
    ZZZ = ZZZ+RLMLT*ZLFDCP (JL,JK)
    ZLFDCP (JL,JK) = 0.0_JPRB

    ZQP1(JL,JK) = ZQP1(JL,JK)-ZZZ*RCPD*RVTMP2/(RCPD+RCPD*RVTMP2*ZQP15(JL,JK))**2
    PAPHP1(JL,JK+1) = PAPHP1(JL,JK+1)+ZDP (JL,JK)
    PAPHP1(JL,JK) = PAPHP1(JL,JK)-ZDP (JL,JK)
    ZDP (JL,JK) = 0.0_JPRB
  ENDDO
ENDDO

! first guess values for T, q, qliq and qice

DO JK=KLEV,1,-1
  DO JL=KIDIA,KFDIA
    PI   (JL,JK) = PI   (JL,JK) + ZI(JL,JK)
    PGTENI(JL,JK)= PGTENI(JL,JK) + PTSPHY*ZI (JL,JK)
    ZI (JL,JK)   = 0.0_JPRB
    
    PL   (JL,JK) = PL   (JL,JK) + ZL(JL,JK)
    PGTENL(JL,JK)= PGTENL(JL,JK) + PTSPHY*ZL (JL,JK)
    ZL (JL,JK)   = 0.0_JPRB

    PQM1 (JL,JK) = PQM1 (JL,JK)+ZQP1 (JL,JK)
    PGTENQ(JL,JK)= PGTENQ(JL,JK)+PTSPHY*ZQP1 (JL,JK)
    PSUPSAT(JL,JK)= PTSPHY*ZQP1 (JL,JK)  ! not initialized by zeros
    ZQP1 (JL,JK) = 0.0_JPRB

    PTM1 (JL,JK) = PTM1 (JL,JK)+ZTP1 (JL,JK)
    PGTENT(JL,JK)= PGTENT(JL,JK)+PTSPHY*ZTP1 (JL,JK)
    ZTP1 (JL,JK) = 0.0_JPRB
  ENDDO
ENDDO

!     ------------------------------------------------------------------

END ASSOCIATE
!IF (LHOOK) CALL DR_HOOK('CLOUDSC2AD',1,ZHOOK_HANDLE)
END SUBROUTINE CLOUDSC2AD
END MODULE CLOUDSC2AD_MOD
